package xolova.blued00r.divinerpg.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelEye extends ModelBase
{
    ModelRenderer ear1;
    ModelRenderer body1;
    ModelRenderer ext1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer leftbackfoot;
    ModelRenderer eye1;
    ModelRenderer cap1;
    ModelRenderer leftbackleg;
    ModelRenderer leftfrontfoot;
    ModelRenderer leftfrontleg;
    ModelRenderer eye2;
    ModelRenderer ext2;
    ModelRenderer cap2;
    ModelRenderer rightbackfoot;
    ModelRenderer rightbackleg;
    ModelRenderer ext3;
    ModelRenderer eye3;
    ModelRenderer cap3;
    ModelRenderer ext4;
    ModelRenderer cap4;
    ModelRenderer eye4;
    ModelRenderer rightfrontleg;
    ModelRenderer rightfrontfoot;
    ModelRenderer head;
    ModelRenderer ear2;
    ModelRenderer ear3;
    ModelRenderer ear4;

    public ModelEye()
    {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.ear1 = new ModelRenderer(this, 0, 22);
        this.ear1.addBox(4.0F, -4.0F, 6.0F, 1, 2, 7);
        this.ear1.setRotationPoint(0.0F, 1.0F, 0.0F);
        this.ear1.setTextureSize(64, 32);
        this.ear1.mirror = true;
        this.setRotation(this.ear1, 1.047198F, 0.0F, 0.0F);
        this.body1 = new ModelRenderer(this, 32, 12);
        this.body1.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 8);
        this.body1.setRotationPoint(-4.0F, 0.0F, -6.0F);
        this.body1.setTextureSize(64, 32);
        this.body1.mirror = true;
        this.setRotation(this.body1, 0.0F, 0.0F, 0.0F);
        this.ext1 = new ModelRenderer(this, 15, 22);
        this.ext1.addBox(-2.0F, -2.0F, -2.0F, 4, 2, 8);
        this.ext1.setRotationPoint(10.0F, 12.0F, 9.0F);
        this.ext1.setTextureSize(64, 32);
        this.ext1.mirror = true;
        this.setRotation(this.ext1, 0.0F, ((float)Math.PI / 4F), 0.0F);
        this.body2 = new ModelRenderer(this, 32, 12);
        this.body2.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 8);
        this.body2.setRotationPoint(-4.0F, 0.0F, 2.0F);
        this.body2.setTextureSize(64, 32);
        this.body2.mirror = true;
        this.setRotation(this.body2, 0.0F, 0.0F, 0.0F);
        this.body3 = new ModelRenderer(this, 32, 12);
        this.body3.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 8);
        this.body3.setRotationPoint(4.0F, 0.0F, -6.0F);
        this.body3.setTextureSize(64, 32);
        this.body3.mirror = true;
        this.setRotation(this.body3, 0.0F, 0.0F, 0.0F);
        this.body4 = new ModelRenderer(this, 32, 12);
        this.body4.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 8);
        this.body4.setRotationPoint(4.0F, 0.0F, 2.0F);
        this.body4.setTextureSize(64, 32);
        this.body4.mirror = true;
        this.setRotation(this.body4, 0.0F, 0.0F, 0.0F);
        this.leftbackfoot = new ModelRenderer(this, 0, 24);
        this.leftbackfoot.addBox(-3.0F, 10.0F, -3.0F, 6, 2, 6);
        this.leftbackfoot.setRotationPoint(14.0F, 12.0F, 13.0F);
        this.leftbackfoot.setTextureSize(64, 32);
        this.leftbackfoot.mirror = true;
        this.setRotation(this.leftbackfoot, 0.0F, 0.0F, 0.0F);
        this.eye1 = new ModelRenderer(this, 42, 0);
        this.eye1.addBox(0.0F, 0.0F, 0.0F, 4, 4, 4);
        this.eye1.setRotationPoint(12.0F, 8.0F, 11.0F);
        this.eye1.setTextureSize(64, 32);
        this.eye1.mirror = true;
        this.setRotation(this.eye1, 0.0F, 0.0F, 0.0F);
        this.cap1 = new ModelRenderer(this, 13, 22);
        this.cap1.addBox(0.0F, 0.0F, 0.0F, 4, 4, 4);
        this.cap1.setRotationPoint(7.0F, 8.0F, 6.0F);
        this.cap1.setTextureSize(64, 32);
        this.cap1.mirror = true;
        this.setRotation(this.cap1, 0.0F, 0.0F, 0.0F);
        this.leftbackleg = new ModelRenderer(this, 0, 16);
        this.leftbackleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.leftbackleg.setRotationPoint(14.0F, 12.0F, 13.0F);
        this.leftbackleg.setTextureSize(64, 32);
        this.leftbackleg.mirror = true;
        this.setRotation(this.leftbackleg, 0.0F, 0.0F, 0.0F);
        this.leftfrontfoot = new ModelRenderer(this, 0, 24);
        this.leftfrontfoot.addBox(-3.0F, 10.0F, -3.0F, 6, 2, 6);
        this.leftfrontfoot.setRotationPoint(14.0F, 12.0F, -13.0F);
        this.leftfrontfoot.setTextureSize(64, 32);
        this.leftfrontfoot.mirror = true;
        this.setRotation(this.leftfrontfoot, 0.0F, 0.0F, 0.0F);
        this.leftfrontleg = new ModelRenderer(this, 0, 16);
        this.leftfrontleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.leftfrontleg.setRotationPoint(14.0F, 12.0F, -13.0F);
        this.leftfrontleg.setTextureSize(64, 32);
        this.leftfrontleg.mirror = true;
        this.setRotation(this.leftfrontleg, 0.0F, 0.0F, 0.0F);
        this.eye2 = new ModelRenderer(this, 42, 0);
        this.eye2.addBox(0.0F, 0.0F, 0.0F, 4, 4, 4);
        this.eye2.setRotationPoint(12.0F, 8.0F, -15.0F);
        this.eye2.setTextureSize(64, 32);
        this.eye2.mirror = true;
        this.setRotation(this.eye2, 0.0F, 0.0F, 0.0F);
        this.ext2 = new ModelRenderer(this, 15, 22);
        this.ext2.addBox(-2.0F, -2.0F, -2.0F, 4, 2, 8);
        this.ext2.setRotationPoint(13.0F, 12.0F, -12.0F);
        this.ext2.setTextureSize(64, 32);
        this.ext2.mirror = true;
        this.setRotation(this.ext2, 0.0F, -((float)Math.PI / 4F), 0.0F);
        this.cap2 = new ModelRenderer(this, 13, 22);
        this.cap2.addBox(0.0F, 0.0F, 0.0F, 4, 4, 4);
        this.cap2.setRotationPoint(7.0F, 8.0F, -10.0F);
        this.cap2.setTextureSize(64, 32);
        this.cap2.mirror = true;
        this.setRotation(this.cap2, 0.0F, 0.0F, 0.0F);
        this.rightbackfoot = new ModelRenderer(this, 0, 24);
        this.rightbackfoot.addBox(-3.0F, 10.0F, -3.0F, 6, 2, 6);
        this.rightbackfoot.setRotationPoint(-13.0F, 12.0F, 13.0F);
        this.rightbackfoot.setTextureSize(64, 32);
        this.rightbackfoot.mirror = true;
        this.setRotation(this.rightbackfoot, 0.0F, 0.0F, 0.0F);
        this.rightbackleg = new ModelRenderer(this, 0, 16);
        this.rightbackleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.rightbackleg.setRotationPoint(-13.0F, 12.0F, 13.0F);
        this.rightbackleg.setTextureSize(64, 32);
        this.rightbackleg.mirror = true;
        this.setRotation(this.rightbackleg, 0.0F, 0.0F, 0.0F);
        this.ext3 = new ModelRenderer(this, 15, 22);
        this.ext3.addBox(-2.0F, -2.0F, -2.0F, 4, 2, 8);
        this.ext3.setRotationPoint(-9.0F, 12.0F, 9.0F);
        this.ext3.setTextureSize(64, 32);
        this.ext3.mirror = true;
        this.setRotation(this.ext3, 0.0F, -((float)Math.PI / 4F), 0.0F);
        this.eye3 = new ModelRenderer(this, 42, 0);
        this.eye3.addBox(0.0F, 0.0F, 0.0F, 4, 4, 4);
        this.eye3.setRotationPoint(-15.0F, 8.0F, 11.0F);
        this.eye3.setTextureSize(64, 32);
        this.eye3.mirror = true;
        this.setRotation(this.eye3, 0.0F, 0.0F, 0.0F);
        this.cap3 = new ModelRenderer(this, 13, 22);
        this.cap3.addBox(0.0F, 0.0F, 0.0F, 4, 4, 4);
        this.cap3.setRotationPoint(-10.0F, 8.0F, 6.0F);
        this.cap3.setTextureSize(64, 32);
        this.cap3.mirror = true;
        this.setRotation(this.cap3, 0.0F, 0.0F, 0.0F);
        this.ext4 = new ModelRenderer(this, 15, 22);
        this.ext4.addBox(-2.0F, -2.0F, -2.0F, 4, 2, 8);
        this.ext4.setRotationPoint(-12.0F, 12.0F, -12.0F);
        this.ext4.setTextureSize(64, 32);
        this.ext4.mirror = true;
        this.setRotation(this.ext4, 0.0F, ((float)Math.PI / 4F), 0.0F);
        this.cap4 = new ModelRenderer(this, 13, 22);
        this.cap4.addBox(0.0F, 0.0F, 0.0F, 4, 4, 4);
        this.cap4.setRotationPoint(-10.0F, 8.0F, -10.0F);
        this.cap4.setTextureSize(64, 32);
        this.cap4.mirror = true;
        this.setRotation(this.cap4, 0.0F, 0.0F, 0.0F);
        this.eye4 = new ModelRenderer(this, 42, 0);
        this.eye4.addBox(0.0F, 0.0F, 0.0F, 4, 4, 4);
        this.eye4.setRotationPoint(-15.0F, 8.0F, -15.0F);
        this.eye4.setTextureSize(64, 32);
        this.eye4.mirror = true;
        this.setRotation(this.eye4, 0.0F, 0.0F, 0.0F);
        this.rightfrontleg = new ModelRenderer(this, 0, 16);
        this.rightfrontleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.rightfrontleg.setRotationPoint(-13.0F, 12.0F, -13.0F);
        this.rightfrontleg.setTextureSize(64, 32);
        this.rightfrontleg.mirror = true;
        this.setRotation(this.rightfrontleg, 0.0F, 0.0F, 0.0F);
        this.rightfrontfoot = new ModelRenderer(this, 0, 24);
        this.rightfrontfoot.addBox(-3.0F, 10.0F, -3.0F, 6, 2, 6);
        this.rightfrontfoot.setRotationPoint(-13.0F, 12.0F, -13.0F);
        this.rightfrontfoot.setTextureSize(64, 32);
        this.rightfrontfoot.mirror = true;
        this.setRotation(this.rightfrontfoot, 0.0F, 0.0F, 0.0F);
        this.head = new ModelRenderer(this, 0, 0);
        this.head.addBox(-4.0F, -9.0F, -4.0F, 8, 8, 8);
        this.head.setRotationPoint(0.0F, 1.0F, 0.0F);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0F, 0.0F, 0.0F);
        this.ear2 = new ModelRenderer(this, 0, 22);
        this.ear2.addBox(4.0F, -7.0F, 5.0F, 1, 2, 7);
        this.ear2.setRotationPoint(0.0F, 1.0F, 0.0F);
        this.ear2.setTextureSize(64, 32);
        this.ear2.mirror = true;
        this.setRotation(this.ear2, 1.047198F, 0.0F, 0.0F);
        this.ear3 = new ModelRenderer(this, 0, 22);
        this.ear3.addBox(-5.0F, -4.0F, 6.0F, 1, 2, 7);
        this.ear3.setRotationPoint(0.0F, 1.0F, 0.0F);
        this.ear3.setTextureSize(64, 32);
        this.ear3.mirror = true;
        this.setRotation(this.ear3, 1.047198F, 0.0F, 0.0F);
        this.ear4 = new ModelRenderer(this, 0, 22);
        this.ear4.addBox(-5.0F, -7.0F, 5.0F, 1, 2, 7);
        this.ear4.setRotationPoint(0.0F, 1.0F, 0.0F);
        this.ear4.setTextureSize(64, 32);
        this.ear4.mirror = true;
        this.setRotation(this.ear4, 1.047198F, 0.0F, 0.0F);
    }

    /**
     * Sets the models various rotation angles then renders the model.
     */
    public void render(Entity var1, float var2, float var3, float var4, float var5, float var6, float var7)
    {
        super.render(var1, var2, var3, var4, var5, var6, var7);
        this.setRotationAngles(var2, var3, var4, var5, var6, var7);
        this.ear1.render(var7);
        this.body1.render(var7);
        this.ext1.render(var7);
        this.body2.render(var7);
        this.body3.render(var7);
        this.body4.render(var7);
        this.leftbackfoot.render(var7);
        this.eye1.render(var7);
        this.cap1.render(var7);
        this.leftbackleg.render(var7);
        this.leftfrontfoot.render(var7);
        this.leftfrontleg.render(var7);
        this.eye2.render(var7);
        this.ext2.render(var7);
        this.cap2.render(var7);
        this.rightbackfoot.render(var7);
        this.rightbackleg.render(var7);
        this.ext3.render(var7);
        this.eye3.render(var7);
        this.cap3.render(var7);
        this.ext4.render(var7);
        this.cap4.render(var7);
        this.eye4.render(var7);
        this.rightfrontleg.render(var7);
        this.rightfrontfoot.render(var7);
        this.head.render(var7);
        this.ear2.render(var7);
        this.ear3.render(var7);
        this.ear4.render(var7);
    }

    private void setRotation(ModelRenderer var1, float var2, float var3, float var4)
    {
        var1.rotateAngleX = var2;
        var1.rotateAngleY = var3;
        var1.rotateAngleZ = var4;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6)
    {
        this.head.rotateAngleY = var4 / (180F / (float)Math.PI);
        this.head.rotateAngleX = var5 / (180F / (float)Math.PI);
        this.ear1.rotateAngleY = var4 / (180F / (float)Math.PI);
        this.ear1.rotateAngleX = var5 / (180F / (float)Math.PI);
        this.ear2.rotateAngleY = var4 / (180F / (float)Math.PI);
        this.ear2.rotateAngleX = var5 / (180F / (float)Math.PI);
        this.ear3.rotateAngleY = var4 / (180F / (float)Math.PI);
        this.ear3.rotateAngleX = var5 / (180F / (float)Math.PI);
        this.ear4.rotateAngleY = var4 / (180F / (float)Math.PI);
        this.ear4.rotateAngleX = var5 / (180F / (float)Math.PI);
        this.rightfrontleg.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.rightbackleg.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.rightfrontfoot.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.rightbackfoot.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.leftfrontleg.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.leftbackleg.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.leftfrontfoot.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.leftbackfoot.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.rightfrontleg.rotateAngleY = 0.0F;
        this.rightbackleg.rotateAngleY = 0.0F;
        this.rightfrontfoot.rotateAngleY = 0.0F;
        this.rightbackfoot.rotateAngleY = 0.0F;
        this.leftfrontleg.rotateAngleY = 0.0F;
        this.leftbackleg.rotateAngleY = 0.0F;
        this.leftfrontfoot.rotateAngleY = 0.0F;
        this.leftbackfoot.rotateAngleY = 0.0F;
    }
}
