package xolova.blued00r.divinerpg.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelRotatick extends ModelBase
{
    ModelRenderer Box8;
    ModelRenderer Body;
    ModelRenderer LegRBT;
    ModelRenderer LegLBT;
    ModelRenderer LegRFT;
    ModelRenderer LegLFT;
    ModelRenderer LegRMT;
    ModelRenderer LegLMT;
    ModelRenderer LegRF;
    ModelRenderer LegLF;
    ModelRenderer LegLM;
    ModelRenderer LegLB;
    ModelRenderer LegRM;
    ModelRenderer LegRB;
    ModelRenderer LegRFB;
    ModelRenderer LegLFB;
    ModelRenderer LegRMB;
    ModelRenderer LegRBB;
    ModelRenderer LegLMB;
    ModelRenderer LegLBB;
    ModelRenderer LegLFC;
    ModelRenderer LegLMC;
    ModelRenderer LegLBC;
    ModelRenderer LegRBC;
    ModelRenderer LegRMC;
    ModelRenderer LegRFC;
    ModelRenderer Box1;
    ModelRenderer Box2;
    ModelRenderer Box3;
    ModelRenderer Box4;
    ModelRenderer Box5;
    ModelRenderer Box6;
    ModelRenderer Box7;
    ModelRenderer Box9;
    ModelRenderer Head;
    ModelRenderer Box10;

    public ModelRotatick()
    {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.Box8 = new ModelRenderer(this, 41, 13);
        this.Box8.addBox(-4.0F, -3.0F, -1.0F, 3, 3, 1);
        this.Box8.setRotationPoint(5.0F, 19.0F, -10.0F);
        this.Box8.setTextureSize(64, 32);
        this.Box8.mirror = true;
        this.setRotation(this.Box8, 0.6320364F, 0.0F, 0.0F);
        this.Body = new ModelRenderer(this, 40, 7);
        this.Body.addBox(-4.0F, -2.0F, -3.0F, 6, 19, 6);
        this.Body.setRotationPoint(0.0F, 14.0F, -3.0F);
        this.Body.setTextureSize(64, 32);
        this.Body.mirror = true;
        this.setRotation(this.Body, ((float)Math.PI / 2F), 0.0F, 0.0F);
        this.LegRBT = new ModelRenderer(this, 42, 15);
        this.LegRBT.addBox(-2.0F, -1.0F, -2.0F, 4, 2, 4);
        this.LegRBT.setRotationPoint(-4.5F, 16.0F, 12.0F);
        this.LegRBT.setTextureSize(64, 32);
        this.LegRBT.mirror = true;
        this.setRotation(this.LegRBT, 0.0F, 0.0F, 0.0F);
        this.LegLBT = new ModelRenderer(this, 42, 15);
        this.LegLBT.addBox(-2.0F, -1.0F, -2.0F, 4, 2, 4);
        this.LegLBT.setRotationPoint(2.5F, 16.0F, 12.0F);
        this.LegLBT.setTextureSize(64, 32);
        this.LegLBT.mirror = true;
        this.setRotation(this.LegLBT, 0.0F, 0.0F, 0.0F);
        this.LegRFT = new ModelRenderer(this, 42, 15);
        this.LegRFT.addBox(-2.0F, -1.0F, -2.0F, 4, 2, 4);
        this.LegRFT.setRotationPoint(-4.5F, 16.0F, -4.0F);
        this.LegRFT.setTextureSize(64, 32);
        this.LegRFT.mirror = true;
        this.setRotation(this.LegRFT, 0.0F, 0.0F, 0.0F);
        this.LegLFT = new ModelRenderer(this, 42, 15);
        this.LegLFT.addBox(-2.0F, -1.0F, -2.0F, 4, 2, 4);
        this.LegLFT.setRotationPoint(2.5F, 16.0F, -4.0F);
        this.LegLFT.setTextureSize(64, 32);
        this.LegLFT.mirror = true;
        this.setRotation(this.LegLFT, 0.0F, 0.0F, 0.0F);
        this.LegRMT = new ModelRenderer(this, 42, 15);
        this.LegRMT.addBox(-2.0F, -1.0F, -1.0F, 4, 2, 4);
        this.LegRMT.setRotationPoint(-4.5F, 16.0F, 2.0F);
        this.LegRMT.setTextureSize(64, 32);
        this.LegRMT.mirror = true;
        this.setRotation(this.LegRMT, 0.0F, 0.0F, 0.0F);
        this.LegLMT = new ModelRenderer(this, 42, 15);
        this.LegLMT.addBox(-2.0F, -1.0F, -1.0F, 4, 2, 4);
        this.LegLMT.setRotationPoint(2.5F, 16.0F, 2.0F);
        this.LegLMT.setTextureSize(64, 32);
        this.LegLMT.mirror = true;
        this.setRotation(this.LegLMT, 0.0F, 0.0F, 0.0F);
        this.LegRF = new ModelRenderer(this, 0, 18);
        this.LegRF.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2);
        this.LegRF.setRotationPoint(-4.5F, 16.0F, -4.0F);
        this.LegRF.setTextureSize(64, 32);
        this.LegRF.mirror = true;
        this.setRotation(this.LegRF, 0.0F, 0.0F, 0.0F);
        this.LegLF = new ModelRenderer(this, 0, 18);
        this.LegLF.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2);
        this.LegLF.setRotationPoint(2.5F, 16.0F, -4.0F);
        this.LegLF.setTextureSize(64, 32);
        this.LegLF.mirror = true;
        this.setRotation(this.LegLF, 0.0F, 0.0F, 0.0F);
        this.LegLM = new ModelRenderer(this, 0, 18);
        this.LegLM.addBox(-1.0F, 0.0F, 0.0F, 2, 8, 2);
        this.LegLM.setRotationPoint(-4.5F, 16.0F, 2.0F);
        this.LegLM.setTextureSize(64, 32);
        this.LegLM.mirror = true;
        this.setRotation(this.LegLM, 0.0F, 0.0F, 0.0F);
        this.LegLB = new ModelRenderer(this, 0, 18);
        this.LegLB.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2);
        this.LegLB.setRotationPoint(-4.5F, 16.0F, 12.0F);
        this.LegLB.setTextureSize(64, 32);
        this.LegLB.mirror = true;
        this.setRotation(this.LegLB, 0.0F, 0.0F, 0.0F);
        this.LegRM = new ModelRenderer(this, 0, 18);
        this.LegRM.addBox(-1.0F, 0.0F, 0.0F, 2, 8, 2);
        this.LegRM.setRotationPoint(2.5F, 16.0F, 2.0F);
        this.LegRM.setTextureSize(64, 32);
        this.LegRM.mirror = true;
        this.setRotation(this.LegRM, 0.0F, 0.0F, 0.0F);
        this.LegRB = new ModelRenderer(this, 0, 18);
        this.LegRB.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2);
        this.LegRB.setRotationPoint(2.5F, 16.0F, 12.0F);
        this.LegRB.setTextureSize(64, 32);
        this.LegRB.mirror = true;
        this.setRotation(this.LegRB, 0.0F, 0.0F, 0.0F);
        this.LegRFB = new ModelRenderer(this, 14, 26);
        this.LegRFB.addBox(-2.0F, 6.0F, -2.0F, 4, 2, 4);
        this.LegRFB.setRotationPoint(-4.5F, 16.0F, -4.0F);
        this.LegRFB.setTextureSize(64, 32);
        this.LegRFB.mirror = true;
        this.setRotation(this.LegRFB, 0.0F, 0.0F, 0.0F);
        this.LegLFB = new ModelRenderer(this, 14, 26);
        this.LegLFB.addBox(-2.0F, 6.0F, -2.0F, 4, 2, 4);
        this.LegLFB.setRotationPoint(2.5F, 16.0F, -4.0F);
        this.LegLFB.setTextureSize(64, 32);
        this.LegLFB.mirror = true;
        this.setRotation(this.LegLFB, 0.0F, 0.0F, 0.0F);
        this.LegRMB = new ModelRenderer(this, 14, 26);
        this.LegRMB.addBox(-2.0F, 6.0F, -1.0F, 4, 2, 4);
        this.LegRMB.setRotationPoint(-4.5F, 16.0F, 2.0F);
        this.LegRMB.setTextureSize(64, 32);
        this.LegRMB.mirror = true;
        this.setRotation(this.LegRMB, 0.0F, 0.0F, 0.0F);
        this.LegRBB = new ModelRenderer(this, 14, 26);
        this.LegRBB.addBox(-2.0F, 6.0F, -2.0F, 4, 2, 4);
        this.LegRBB.setRotationPoint(-4.5F, 16.0F, 12.0F);
        this.LegRBB.setTextureSize(64, 32);
        this.LegRBB.mirror = true;
        this.setRotation(this.LegRBB, 0.0F, 0.0F, 0.0F);
        this.LegLMB = new ModelRenderer(this, 14, 26);
        this.LegLMB.addBox(-2.0F, 6.0F, -1.0F, 4, 2, 4);
        this.LegLMB.setRotationPoint(2.5F, 16.0F, 2.0F);
        this.LegLMB.setTextureSize(64, 32);
        this.LegLMB.mirror = true;
        this.setRotation(this.LegLMB, 0.0F, 0.0F, 0.0F);
        this.LegLBB = new ModelRenderer(this, 14, 26);
        this.LegLBB.addBox(-2.0F, 6.0F, -2.0F, 4, 2, 4);
        this.LegLBB.setRotationPoint(2.5F, 16.0F, 12.0F);
        this.LegLBB.setTextureSize(64, 32);
        this.LegLBB.mirror = true;
        this.setRotation(this.LegLBB, 0.0F, 0.0F, 0.0F);
        this.LegLFC = new ModelRenderer(this, 14, 18);
        this.LegLFC.addBox(-2.0F, 3.0F, -2.0F, 4, 1, 4);
        this.LegLFC.setRotationPoint(2.5F, 16.0F, -4.0F);
        this.LegLFC.setTextureSize(64, 32);
        this.LegLFC.mirror = true;
        this.setRotation(this.LegLFC, 0.0F, 0.0F, 0.0F);
        this.LegLMC = new ModelRenderer(this, 14, 18);
        this.LegLMC.addBox(-2.0F, 3.0F, -1.0F, 4, 1, 4);
        this.LegLMC.setRotationPoint(2.5F, 16.0F, 2.0F);
        this.LegLMC.setTextureSize(64, 32);
        this.LegLMC.mirror = true;
        this.setRotation(this.LegLMC, 0.0F, 0.0F, 0.0F);
        this.LegLBC = new ModelRenderer(this, 14, 18);
        this.LegLBC.addBox(-2.0F, 3.0F, -2.0F, 4, 1, 4);
        this.LegLBC.setRotationPoint(2.5F, 16.0F, 12.0F);
        this.LegLBC.setTextureSize(64, 32);
        this.LegLBC.mirror = true;
        this.setRotation(this.LegLBC, 0.0F, 0.0F, 0.0F);
        this.LegRBC = new ModelRenderer(this, 14, 18);
        this.LegRBC.addBox(-2.0F, 3.0F, -2.0F, 4, 1, 4);
        this.LegRBC.setRotationPoint(-4.5F, 16.0F, 12.0F);
        this.LegRBC.setTextureSize(64, 32);
        this.LegRBC.mirror = true;
        this.setRotation(this.LegRBC, 0.0F, 0.0F, 0.0F);
        this.LegRMC = new ModelRenderer(this, 14, 18);
        this.LegRMC.addBox(-2.0F, 3.0F, -1.0F, 4, 1, 4);
        this.LegRMC.setRotationPoint(-4.5F, 16.0F, 2.0F);
        this.LegRMC.setTextureSize(64, 32);
        this.LegRMC.mirror = true;
        this.setRotation(this.LegRMC, 0.0F, 0.0F, 0.0F);
        this.LegRFC = new ModelRenderer(this, 14, 18);
        this.LegRFC.addBox(-2.0F, 3.0F, -2.0F, 4, 1, 4);
        this.LegRFC.setRotationPoint(-4.5F, 16.0F, -4.0F);
        this.LegRFC.setTextureSize(64, 32);
        this.LegRFC.mirror = true;
        this.setRotation(this.LegRFC, 0.0F, 0.0F, 0.0F);
        this.Box1 = new ModelRenderer(this, 42, 21);
        this.Box1.addBox(-2.0F, -3.0F, 3.0F, 4, 4, 4);
        this.Box1.setRotationPoint(-1.0F, 11.0F, 7.0F);
        this.Box1.setTextureSize(64, 32);
        this.Box1.mirror = true;
        this.setRotation(this.Box1, 0.0F, 0.0F, 0.0F);
        this.Box2 = new ModelRenderer(this, 41, 13);
        this.Box2.addBox(-4.0F, -3.0F, -1.0F, 3, 3, 1);
        this.Box2.setRotationPoint(-2.0F, 19.0F, -10.0F);
        this.Box2.setTextureSize(64, 32);
        this.Box2.mirror = true;
        this.setRotation(this.Box2, 0.6320364F, 0.0F, 0.0F);
        this.Box3 = new ModelRenderer(this, 45, 16);
        this.Box3.addBox(-3.0F, 0.0F, -2.0F, 2, 2, 2);
        this.Box3.setRotationPoint(5.0F, 13.5F, -6.0F);
        this.Box3.setTextureSize(64, 32);
        this.Box3.mirror = true;
        this.setRotation(this.Box3, 0.0F, 0.0F, 0.0F);
        this.Box4 = new ModelRenderer(this, 42, 12);
        this.Box4.addBox(-2.0F, -3.0F, -2.0F, 4, 7, 4);
        this.Box4.setRotationPoint(-1.0F, 11.5F, -3.0F);
        this.Box4.setTextureSize(64, 32);
        this.Box4.mirror = true;
        this.setRotation(this.Box4, 0.0F, 0.0F, 0.0F);
        this.Box5 = new ModelRenderer(this, 42, 12);
        this.Box5.addBox(-2.0F, -3.0F, -2.0F, 4, 6, 4);
        this.Box5.setRotationPoint(-1.0F, 11.5F, 2.0F);
        this.Box5.setTextureSize(64, 32);
        this.Box5.mirror = true;
        this.setRotation(this.Box5, 0.0F, 0.0F, 0.0F);
        this.Box6 = new ModelRenderer(this, 42, 21);
        this.Box6.addBox(-2.0F, -3.0F, -2.0F, 4, 6, 4);
        this.Box6.setRotationPoint(-1.0F, 11.5F, 7.0F);
        this.Box6.setTextureSize(64, 32);
        this.Box6.mirror = true;
        this.setRotation(this.Box6, 0.0F, 0.0F, 0.0F);
        this.Box7 = new ModelRenderer(this, 41, 13);
        this.Box7.addBox(-4.0F, -3.0F, -1.0F, 1, 1, 6);
        this.Box7.setRotationPoint(6.0F, 19.5F, -9.0F);
        this.Box7.setTextureSize(64, 32);
        this.Box7.mirror = true;
        this.setRotation(this.Box7, 0.6320364F, 0.0F, 0.0F);
        this.Box9 = new ModelRenderer(this, 41, 13);
        this.Box9.addBox(-4.0F, -3.0F, -1.0F, 1, 1, 6);
        this.Box9.setRotationPoint(-1.0F, 19.5F, -9.0F);
        this.Box9.setTextureSize(64, 32);
        this.Box9.mirror = true;
        this.setRotation(this.Box9, 0.6320364F, 0.0F, 0.0F);
        this.Head = new ModelRenderer(this, 0, 0);
        this.Head.addBox(-3.0F, -3.0F, -2.0F, 6, 6, 4);
        this.Head.setRotationPoint(-1.0F, 13.5F, -7.0F);
        this.Head.setTextureSize(64, 32);
        this.Head.mirror = true;
        this.setRotation(this.Head, 0.0F, 0.0F, 0.0F);
        this.Box10 = new ModelRenderer(this, 45, 16);
        this.Box10.addBox(-3.0F, 0.0F, -2.0F, 2, 2, 2);
        this.Box10.setRotationPoint(-3.0F, 13.5F, -6.0F);
        this.Box10.setTextureSize(64, 32);
        this.Box10.mirror = true;
        this.setRotation(this.Box10, 0.0F, 0.0F, 0.0F);
    }

    /**
     * Sets the models various rotation angles then renders the model.
     */
    public void render(Entity var1, float var2, float var3, float var4, float var5, float var6, float var7)
    {
        super.render(var1, var2, var3, var4, var5, var6, var7);
        this.setRotationAngles(var2, var3, var4, var5, var6, var7);
        this.Box8.render(var7);
        this.Body.render(var7);
        this.LegRBT.render(var7);
        this.LegLBT.render(var7);
        this.LegRFT.render(var7);
        this.LegLFT.render(var7);
        this.LegRMT.render(var7);
        this.LegLMT.render(var7);
        this.LegRF.render(var7);
        this.LegLF.render(var7);
        this.LegLM.render(var7);
        this.LegLB.render(var7);
        this.LegRM.render(var7);
        this.LegRB.render(var7);
        this.LegRFB.render(var7);
        this.LegLFB.render(var7);
        this.LegRMB.render(var7);
        this.LegRBB.render(var7);
        this.LegLMB.render(var7);
        this.LegLBB.render(var7);
        this.LegLFC.render(var7);
        this.LegLMC.render(var7);
        this.LegLBC.render(var7);
        this.LegRBC.render(var7);
        this.LegRMC.render(var7);
        this.LegRFC.render(var7);
        this.Box1.render(var7);
        this.Box2.render(var7);
        this.Box3.render(var7);
        this.Box4.render(var7);
        this.Box5.render(var7);
        this.Box6.render(var7);
        this.Box7.render(var7);
        this.Box9.render(var7);
        this.Head.render(var7);
        this.Box10.render(var7);
    }

    private void setRotation(ModelRenderer var1, float var2, float var3, float var4)
    {
        var1.rotateAngleX = var2;
        var1.rotateAngleY = var3;
        var1.rotateAngleZ = var4;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6)
    {
        this.Head.rotateAngleY = var4 / (180F / (float)Math.PI);
        this.Head.rotateAngleX = var5 / (180F / (float)Math.PI);
        this.LegRBT.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegLB.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegRBB.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegRMT.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegLM.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegRMB.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegRFT.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegLF.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegRFB.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegRFC.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegRMC.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegRBC.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.LegLBT.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegRB.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegLBB.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegLMT.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegRM.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegLMB.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegLFT.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegRF.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegLFB.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegLFC.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegLMC.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegLFC.rotateAngleX = MathHelper.cos((float)((double)(var1 * 0.6662F) + Math.PI)) * 1.4F * var2;
        this.LegRBT.rotateAngleY = 0.0F;
        this.LegRB.rotateAngleY = 0.0F;
        this.LegRBB.rotateAngleY = 0.0F;
        this.LegRMT.rotateAngleY = 0.0F;
        this.LegRM.rotateAngleY = 0.0F;
        this.LegRMB.rotateAngleY = 0.0F;
        this.LegRFT.rotateAngleY = 0.0F;
        this.LegRF.rotateAngleY = 0.0F;
        this.LegRFB.rotateAngleY = 0.0F;
        this.LegLBT.rotateAngleY = 0.0F;
        this.LegLB.rotateAngleY = 0.0F;
        this.LegLBB.rotateAngleY = 0.0F;
        this.LegLMT.rotateAngleY = 0.0F;
        this.LegLM.rotateAngleY = 0.0F;
        this.LegLMB.rotateAngleY = 0.0F;
        this.LegLFT.rotateAngleY = 0.0F;
        this.LegLF.rotateAngleY = 0.0F;
        this.LegLFB.rotateAngleY = 0.0F;
    }
}
