package xolova.blued00r.divinerpg.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelDenseDemon extends ModelBase
{
    ModelRenderer Main_Body;
    ModelRenderer Lower_Body;
    ModelRenderer Legbottom1;
    ModelRenderer Legbottom2;
    ModelRenderer Legbottom3;
    ModelRenderer Legbottom4;
    ModelRenderer Legbottom5;
    ModelRenderer Legbottom6;
    ModelRenderer Legbottom7;
    ModelRenderer Legbottom8;
    ModelRenderer Legbottom9;
    ModelRenderer Legbottom10;
    ModelRenderer Legbottom11;
    ModelRenderer Legbottom12;
    ModelRenderer Legbottom13;
    ModelRenderer Legbottom14;
    ModelRenderer Legbottom15;
    ModelRenderer Legbottom16;
    ModelRenderer Legbottom17;
    ModelRenderer Legbottom18;
    ModelRenderer Legbottom19;
    ModelRenderer Legbottom20;
    ModelRenderer Legbottom21;
    ModelRenderer Legbottom22;
    ModelRenderer Legbottom23;
    ModelRenderer Legbottom24;
    ModelRenderer Legbottom25;

    public ModelDenseDemon()
    {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.Main_Body = new ModelRenderer(this, 0, 0);
        this.Main_Body.addBox(0.0F, 0.0F, 0.0F, 10, 6, 10);
        this.Main_Body.setRotationPoint(-6.0F, 6.0F, 2.0F);
        this.Main_Body.setTextureSize(64, 32);
        this.Main_Body.mirror = true;
        this.setRotation(this.Main_Body, 0.0F, ((float)Math.PI / 2F), 0.0F);
        this.Lower_Body = new ModelRenderer(this, 39, 20);
        this.Lower_Body.addBox(0.0F, 0.0F, 0.0F, 6, 6, 6);
        this.Lower_Body.setRotationPoint(-4.0F, 9.0F, 0.0F);
        this.Lower_Body.setTextureSize(64, 32);
        this.Lower_Body.mirror = true;
        this.setRotation(this.Lower_Body, 0.0F, ((float)Math.PI / 2F), 0.0F);
        this.Legbottom1 = new ModelRenderer(this, 14, 5);
        this.Legbottom1.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom1.setRotationPoint(4.0F, 8.0F, 0.0F);
        this.Legbottom1.setTextureSize(64, 32);
        this.Legbottom1.mirror = true;
        this.setRotation(this.Legbottom1, 0.0F, 0.0F, 0.0F);
        this.Legbottom2 = new ModelRenderer(this, 14, 5);
        this.Legbottom2.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom2.setRotationPoint(4.0F, 8.0F, -7.0F);
        this.Legbottom2.setTextureSize(64, 32);
        this.Legbottom2.mirror = true;
        this.setRotation(this.Legbottom2, 0.0F, 0.0F, 0.0F);
        this.Legbottom3 = new ModelRenderer(this, 14, 18);
        this.Legbottom3.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom3.setRotationPoint(4.0F, 1.0F, -5.0F);
        this.Legbottom3.setTextureSize(64, 32);
        this.Legbottom3.mirror = true;
        this.setRotation(this.Legbottom3, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom4 = new ModelRenderer(this, 14, 18);
        this.Legbottom4.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom4.setRotationPoint(4.0F, 1.0F, 2.0F);
        this.Legbottom4.setTextureSize(64, 32);
        this.Legbottom4.mirror = true;
        this.setRotation(this.Legbottom4, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom5 = new ModelRenderer(this, 14, 18);
        this.Legbottom5.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom5.setRotationPoint(-2.0F, 15.0F, -4.0F);
        this.Legbottom5.setTextureSize(64, 32);
        this.Legbottom5.mirror = true;
        this.setRotation(this.Legbottom5, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom6 = new ModelRenderer(this, 14, 18);
        this.Legbottom6.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom6.setRotationPoint(2.0F, 15.0F, -4.0F);
        this.Legbottom6.setTextureSize(64, 32);
        this.Legbottom6.mirror = true;
        this.setRotation(this.Legbottom6, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom7 = new ModelRenderer(this, 14, 18);
        this.Legbottom7.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom7.setRotationPoint(-2.0F, 15.0F, 0.0F);
        this.Legbottom7.setTextureSize(64, 32);
        this.Legbottom7.mirror = true;
        this.setRotation(this.Legbottom7, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom8 = new ModelRenderer(this, 14, 18);
        this.Legbottom8.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom8.setRotationPoint(2.0F, 15.0F, 0.0F);
        this.Legbottom8.setTextureSize(64, 32);
        this.Legbottom8.mirror = true;
        this.setRotation(this.Legbottom8, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom9 = new ModelRenderer(this, 14, 18);
        this.Legbottom9.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom9.setRotationPoint(0.0F, 1.0F, 2.0F);
        this.Legbottom9.setTextureSize(64, 32);
        this.Legbottom9.mirror = true;
        this.setRotation(this.Legbottom9, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom10 = new ModelRenderer(this, 14, 18);
        this.Legbottom10.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom10.setRotationPoint(0.0F, 1.0F, -5.0F);
        this.Legbottom10.setTextureSize(64, 32);
        this.Legbottom10.mirror = true;
        this.setRotation(this.Legbottom10, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom11 = new ModelRenderer(this, 14, 18);
        this.Legbottom11.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom11.setRotationPoint(4.0F, 1.0F, -2.0F);
        this.Legbottom11.setTextureSize(64, 32);
        this.Legbottom11.mirror = true;
        this.setRotation(this.Legbottom11, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom12 = new ModelRenderer(this, 14, 18);
        this.Legbottom12.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom12.setRotationPoint(0.0F, 1.0F, -2.0F);
        this.Legbottom12.setTextureSize(64, 32);
        this.Legbottom12.mirror = true;
        this.setRotation(this.Legbottom12, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom13 = new ModelRenderer(this, 14, 5);
        this.Legbottom13.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom13.setRotationPoint(4.0F, 8.0F, -4.0F);
        this.Legbottom13.setTextureSize(64, 32);
        this.Legbottom13.mirror = true;
        this.setRotation(this.Legbottom13, 0.0F, 0.0F, 0.0F);
        this.Legbottom14 = new ModelRenderer(this, 14, 18);
        this.Legbottom14.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom14.setRotationPoint(-4.0F, 1.0F, -5.0F);
        this.Legbottom14.setTextureSize(64, 32);
        this.Legbottom14.mirror = true;
        this.setRotation(this.Legbottom14, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom15 = new ModelRenderer(this, 14, 18);
        this.Legbottom15.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom15.setRotationPoint(-4.0F, 1.0F, -2.0F);
        this.Legbottom15.setTextureSize(64, 32);
        this.Legbottom15.mirror = true;
        this.setRotation(this.Legbottom15, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom16 = new ModelRenderer(this, 14, 18);
        this.Legbottom16.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Legbottom16.setRotationPoint(-4.0F, 1.0F, 2.0F);
        this.Legbottom16.setTextureSize(64, 32);
        this.Legbottom16.mirror = true;
        this.setRotation(this.Legbottom16, -((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.0F);
        this.Legbottom17 = new ModelRenderer(this, 14, 5);
        this.Legbottom17.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom17.setRotationPoint(4.0F, 5.0F, -7.0F);
        this.Legbottom17.setTextureSize(64, 32);
        this.Legbottom17.mirror = true;
        this.setRotation(this.Legbottom17, 0.0F, 0.0F, 0.0F);
        this.Legbottom18 = new ModelRenderer(this, 14, 5);
        this.Legbottom18.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom18.setRotationPoint(4.0F, 5.0F, -4.0F);
        this.Legbottom18.setTextureSize(64, 32);
        this.Legbottom18.mirror = true;
        this.setRotation(this.Legbottom18, 0.0F, 0.0F, 0.0F);
        this.Legbottom19 = new ModelRenderer(this, 14, 5);
        this.Legbottom19.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom19.setRotationPoint(4.0F, 5.0F, 0.0F);
        this.Legbottom19.setTextureSize(64, 32);
        this.Legbottom19.mirror = true;
        this.setRotation(this.Legbottom19, 0.0F, 0.0F, 0.0F);
        this.Legbottom20 = new ModelRenderer(this, 14, 5);
        this.Legbottom20.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom20.setRotationPoint(-9.0F, 5.0F, -7.0F);
        this.Legbottom20.setTextureSize(64, 32);
        this.Legbottom20.mirror = true;
        this.setRotation(this.Legbottom20, 0.0F, 0.0F, 0.0F);
        this.Legbottom21 = new ModelRenderer(this, 14, 5);
        this.Legbottom21.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom21.setRotationPoint(-9.0F, 5.0F, -4.0F);
        this.Legbottom21.setTextureSize(64, 32);
        this.Legbottom21.mirror = true;
        this.setRotation(this.Legbottom21, 0.0F, 0.0F, 0.0F);
        this.Legbottom22 = new ModelRenderer(this, 14, 5);
        this.Legbottom22.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom22.setRotationPoint(-9.0F, 5.0F, 0.0F);
        this.Legbottom22.setTextureSize(64, 32);
        this.Legbottom22.mirror = true;
        this.setRotation(this.Legbottom22, 0.0F, 0.0F, 0.0F);
        this.Legbottom23 = new ModelRenderer(this, 14, 5);
        this.Legbottom23.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom23.setRotationPoint(-9.0F, 8.0F, 0.0F);
        this.Legbottom23.setTextureSize(64, 32);
        this.Legbottom23.mirror = true;
        this.setRotation(this.Legbottom23, 0.0F, 0.0F, 0.0F);
        this.Legbottom24 = new ModelRenderer(this, 14, 5);
        this.Legbottom24.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom24.setRotationPoint(-9.0F, 8.0F, -4.0F);
        this.Legbottom24.setTextureSize(64, 32);
        this.Legbottom24.mirror = true;
        this.setRotation(this.Legbottom24, 0.0F, 0.0F, 0.0F);
        this.Legbottom25 = new ModelRenderer(this, 14, 5);
        this.Legbottom25.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
        this.Legbottom25.setRotationPoint(-9.0F, 8.0F, -7.0F);
        this.Legbottom25.setTextureSize(64, 32);
        this.Legbottom25.mirror = true;
        this.setRotation(this.Legbottom25, 0.0F, 0.0F, 0.0F);
    }

    /**
     * Sets the models various rotation angles then renders the model.
     */
    public void render(Entity var1, float var2, float var3, float var4, float var5, float var6, float var7)
    {
        super.render(var1, var2, var3, var4, var5, var6, var7);
        this.setRotationAngles(var2, var3, var4, var5, var6, var7);
        this.Main_Body.render(var7);
        this.Lower_Body.render(var7);
        this.Legbottom1.render(var7);
        this.Legbottom2.render(var7);
        this.Legbottom3.render(var7);
        this.Legbottom4.render(var7);
        this.Legbottom5.render(var7);
        this.Legbottom6.render(var7);
        this.Legbottom7.render(var7);
        this.Legbottom8.render(var7);
        this.Legbottom9.render(var7);
        this.Legbottom10.render(var7);
        this.Legbottom11.render(var7);
        this.Legbottom12.render(var7);
        this.Legbottom13.render(var7);
        this.Legbottom14.render(var7);
        this.Legbottom15.render(var7);
        this.Legbottom16.render(var7);
        this.Legbottom17.render(var7);
        this.Legbottom18.render(var7);
        this.Legbottom19.render(var7);
        this.Legbottom20.render(var7);
        this.Legbottom21.render(var7);
        this.Legbottom22.render(var7);
        this.Legbottom23.render(var7);
        this.Legbottom24.render(var7);
        this.Legbottom25.render(var7);
    }

    private void setRotation(ModelRenderer var1, float var2, float var3, float var4)
    {
        var1.rotateAngleX = var2;
        var1.rotateAngleY = var3;
        var1.rotateAngleZ = var4;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6)
    {
        this.Legbottom1.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom2.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom3.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom4.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom5.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom6.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom7.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom8.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom9.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom10.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom11.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom12.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom13.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom14.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom15.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom16.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom17.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom18.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom19.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom20.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom21.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom22.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom23.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom24.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
        this.Legbottom25.rotateAngleX = 0.2F * MathHelper.sin(var3 * 0.3F) + 0.4F;
    }
}
