package xolova.blued00r.divinerpg.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelSoulFiend extends ModelBase
{
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarmext;
    ModelRenderer leftarmext;
    ModelRenderer rightlegcap;
    ModelRenderer leftlegcap;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer back;
    ModelRenderer back2;
    ModelRenderer back3;
    ModelRenderer back4;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
    ModelRenderer leftarm;
    ModelRenderer rightarm;
    ModelRenderer leftfoot;
    ModelRenderer rightfoot;
    ModelRenderer back5;
    ModelRenderer back6;
    ModelRenderer back7;
    ModelRenderer back8;
    ModelRenderer back9;
    ModelRenderer back10;
    ModelRenderer back11;
    ModelRenderer back12;

    public ModelSoulFiend()
    {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.head = new ModelRenderer(this, 0, 0);
        this.head.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8);
        this.head.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0F, 0.0F, 0.0F);
        this.body = new ModelRenderer(this, 16, 16);
        this.body.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4);
        this.body.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body.setTextureSize(64, 32);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0F, 0.0F, 0.0F);
        this.rightarmext = new ModelRenderer(this, 40, 16);
        this.rightarmext.addBox(1.0F, -2.0F, -2.0F, 3, 3, 4);
        this.rightarmext.setRotationPoint(-8.0F, 2.0F, 0.0F);
        this.rightarmext.setTextureSize(64, 32);
        this.rightarmext.mirror = true;
        this.setRotation(this.rightarmext, 0.0F, 0.0F, 0.0F);
        this.leftarmext = new ModelRenderer(this, 40, 16);
        this.leftarmext.addBox(-4.0F, -2.0F, -2.0F, 3, 3, 4);
        this.leftarmext.setRotationPoint(8.0F, 2.0F, 0.0F);
        this.leftarmext.setTextureSize(64, 32);
        this.leftarmext.mirror = true;
        this.setRotation(this.leftarmext, 0.0F, 0.0F, 0.0F);
        this.rightlegcap = new ModelRenderer(this, 0, 16);
        this.rightlegcap.addBox(-3.0F, -4.0F, -3.0F, 6, 5, 6);
        this.rightlegcap.setRotationPoint(-4.0F, 12.0F, 0.0F);
        this.rightlegcap.setTextureSize(64, 32);
        this.rightlegcap.mirror = true;
        this.setRotation(this.rightlegcap, 0.0F, 0.0F, 0.0F);
        this.leftlegcap = new ModelRenderer(this, 0, 16);
        this.leftlegcap.addBox(-3.0F, -4.0F, -3.0F, 6, 5, 6);
        this.leftlegcap.setRotationPoint(4.0F, 12.0F, 0.0F);
        this.leftlegcap.setTextureSize(64, 32);
        this.leftlegcap.mirror = true;
        this.setRotation(this.leftlegcap, 0.0F, 0.0F, 0.0F);
        this.Shape1 = new ModelRenderer(this, 8, 0);
        this.Shape1.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Shape1.setRotationPoint(2.0F, -8.0F, -9.0F);
        this.Shape1.setTextureSize(64, 32);
        this.Shape1.mirror = true;
        this.setRotation(this.Shape1, 0.0F, 0.0F, 0.0F);
        this.Shape2 = new ModelRenderer(this, 8, 0);
        this.Shape2.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Shape2.setRotationPoint(-4.0F, -8.0F, -9.0F);
        this.Shape2.setTextureSize(64, 32);
        this.Shape2.mirror = true;
        this.setRotation(this.Shape2, 0.0F, 0.0F, 0.0F);
        this.Shape3 = new ModelRenderer(this, 9, 0);
        this.Shape3.addBox(0.0F, 0.0F, 0.0F, 4, 2, 2);
        this.Shape3.setRotationPoint(4.0F, -6.0F, -4.0F);
        this.Shape3.setTextureSize(64, 32);
        this.Shape3.mirror = true;
        this.setRotation(this.Shape3, 0.0F, 0.0F, 0.0F);
        this.Shape4 = new ModelRenderer(this, 9, 0);
        this.Shape4.addBox(0.0F, 0.0F, 0.0F, 4, 2, 2);
        this.Shape4.setRotationPoint(-8.0F, -6.0F, -4.0F);
        this.Shape4.setTextureSize(64, 32);
        this.Shape4.mirror = true;
        this.setRotation(this.Shape4, 0.0F, 0.0F, 0.0F);
        this.Shape5 = new ModelRenderer(this, 9, 0);
        this.Shape5.addBox(0.0F, 0.0F, 0.0F, 4, 2, 2);
        this.Shape5.setRotationPoint(4.0F, -3.0F, -4.0F);
        this.Shape5.setTextureSize(64, 32);
        this.Shape5.mirror = true;
        this.setRotation(this.Shape5, 0.0F, 0.0F, 0.0F);
        this.Shape6 = new ModelRenderer(this, 9, 0);
        this.Shape6.addBox(0.0F, 0.0F, 0.0F, 4, 2, 2);
        this.Shape6.setRotationPoint(-8.0F, -3.0F, -4.0F);
        this.Shape6.setTextureSize(64, 32);
        this.Shape6.mirror = true;
        this.setRotation(this.Shape6, 0.0F, 0.0F, 0.0F);
        this.Shape7 = new ModelRenderer(this, 8, 0);
        this.Shape7.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Shape7.setRotationPoint(6.0F, -6.0F, -9.0F);
        this.Shape7.setTextureSize(64, 32);
        this.Shape7.mirror = true;
        this.setRotation(this.Shape7, 0.0F, 0.0F, 0.0F);
        this.Shape8 = new ModelRenderer(this, 8, 0);
        this.Shape8.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Shape8.setRotationPoint(6.0F, -3.0F, -9.0F);
        this.Shape8.setTextureSize(64, 32);
        this.Shape8.mirror = true;
        this.setRotation(this.Shape8, 0.0F, 0.0F, 0.0F);
        this.Shape9 = new ModelRenderer(this, 8, 0);
        this.Shape9.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Shape9.setRotationPoint(-8.0F, -6.0F, -9.0F);
        this.Shape9.setTextureSize(64, 32);
        this.Shape9.mirror = true;
        this.setRotation(this.Shape9, 0.0F, 0.0F, 0.0F);
        this.Shape10 = new ModelRenderer(this, 8, 0);
        this.Shape10.addBox(0.0F, 0.0F, 0.0F, 2, 2, 5);
        this.Shape10.setRotationPoint(-8.0F, -3.0F, -9.0F);
        this.Shape10.setTextureSize(64, 32);
        this.Shape10.mirror = true;
        this.setRotation(this.Shape10, 0.0F, 0.0F, 0.0F);
        this.back = new ModelRenderer(this, 4, 0);
        this.back.addBox(0.0F, 0.0F, 0.0F, 4, 4, 5);
        this.back.setRotationPoint(-2.0F, 4.0F, 2.0F);
        this.back.setTextureSize(64, 32);
        this.back.mirror = true;
        this.setRotation(this.back, 0.0F, 0.0F, 0.0F);
        this.back2 = new ModelRenderer(this, 34, 26);
        this.back2.addBox(0.0F, 0.0F, 0.0F, 12, 2, 2);
        this.back2.setRotationPoint(-12.0F, 13.0F, 4.0F);
        this.back2.setTextureSize(64, 32);
        this.back2.mirror = true;
        this.setRotation(this.back2, 0.0F, 0.0F, -0.6108652F);
        this.back3 = new ModelRenderer(this, 15, 25);
        this.back3.addBox(0.0F, 0.0F, 0.0F, 9, 2, 2);
        this.back3.setRotationPoint(8.0F, 4.0F, 5.0F);
        this.back3.setTextureSize(64, 32);
        this.back3.mirror = true;
        this.setRotation(this.back3, 0.0F, 0.0F, -((float)Math.PI / 2F));
        this.back4 = new ModelRenderer(this, 15, 25);
        this.back4.addBox(0.0F, -1.0F, 0.0F, 9, 2, 2);
        this.back4.setRotationPoint(-9.0F, 4.0F, 5.0F);
        this.back4.setTextureSize(64, 32);
        this.back4.mirror = true;
        this.setRotation(this.back4, 0.0F, 0.0F, -((float)Math.PI / 2F));
        this.leftleg = new ModelRenderer(this, 0, 16);
        this.leftleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.leftleg.setRotationPoint(4.0F, 12.0F, 0.0F);
        this.leftleg.setTextureSize(64, 32);
        this.leftleg.mirror = true;
        this.setRotation(this.leftleg, 0.0F, 0.0F, 0.0F);
        this.rightleg = new ModelRenderer(this, 0, 16);
        this.rightleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.rightleg.setRotationPoint(-4.0F, 12.0F, 0.0F);
        this.rightleg.setTextureSize(64, 32);
        this.rightleg.mirror = true;
        this.setRotation(this.rightleg, 0.0F, 0.0F, 0.0F);
        this.leftarm = new ModelRenderer(this, 40, 3);
        this.leftarm.addBox(-1.0F, -2.0F, -2.0F, 4, 20, 4);
        this.leftarm.setRotationPoint(8.0F, 2.0F, 0.0F);
        this.leftarm.setTextureSize(64, 32);
        this.leftarm.mirror = true;
        this.setRotation(this.leftarm, 0.0F, 0.0F, 0.0F);
        this.rightarm = new ModelRenderer(this, 40, 3);
        this.rightarm.addBox(-3.0F, -2.0F, -2.0F, 4, 20, 4);
        this.rightarm.setRotationPoint(-8.0F, 2.0F, 0.0F);
        this.rightarm.setTextureSize(64, 32);
        this.rightarm.mirror = true;
        this.setRotation(this.rightarm, 0.0F, 0.0F, 0.0F);
        this.leftfoot = new ModelRenderer(this, 0, 16);
        this.leftfoot.addBox(-3.0F, 9.0F, -3.0F, 6, 3, 6);
        this.leftfoot.setRotationPoint(4.0F, 12.0F, 0.0F);
        this.leftfoot.setTextureSize(64, 32);
        this.leftfoot.mirror = true;
        this.setRotation(this.leftfoot, 0.0F, 0.0F, 0.0F);
        this.rightfoot = new ModelRenderer(this, 0, 16);
        this.rightfoot.addBox(-3.0F, 9.0F, -3.0F, 6, 3, 6);
        this.rightfoot.setRotationPoint(-4.0F, 12.0F, 0.0F);
        this.rightfoot.setTextureSize(64, 32);
        this.rightfoot.mirror = true;
        this.setRotation(this.rightfoot, 0.0F, 0.0F, 0.0F);
        this.back5 = new ModelRenderer(this, 4, 0);
        this.back5.addBox(0.0F, 0.0F, 0.0F, 4, 4, 5);
        this.back5.setRotationPoint(-2.0F, 0.0F, 2.0F);
        this.back5.setTextureSize(64, 32);
        this.back5.mirror = true;
        this.setRotation(this.back5, 0.0F, 0.0F, 0.0F);
        this.back6 = new ModelRenderer(this, 8, 0);
        this.back6.addBox(0.0F, 0.0F, 0.0F, 5, 2, 2);
        this.back6.setRotationPoint(2.0F, 0.0F, 5.0F);
        this.back6.setTextureSize(64, 32);
        this.back6.mirror = true;
        this.setRotation(this.back6, 0.0F, 0.0F, 0.0F);
        this.back7 = new ModelRenderer(this, 15, 25);
        this.back7.addBox(0.0F, 0.0F, 0.0F, 9, 2, 2);
        this.back7.setRotationPoint(5.0F, 0.0F, 5.0F);
        this.back7.setTextureSize(64, 32);
        this.back7.mirror = true;
        this.setRotation(this.back7, 0.0F, 0.0F, -((float)Math.PI / 2F));
        this.back8 = new ModelRenderer(this, 8, 0);
        this.back8.addBox(0.0F, 0.0F, 0.0F, 5, 2, 2);
        this.back8.setRotationPoint(-7.0F, 0.0F, 5.0F);
        this.back8.setTextureSize(64, 32);
        this.back8.mirror = true;
        this.setRotation(this.back8, 0.0F, 0.0F, 0.0F);
        this.back9 = new ModelRenderer(this, 15, 25);
        this.back9.addBox(0.0F, -1.0F, 0.0F, 9, 2, 2);
        this.back9.setRotationPoint(-6.0F, 0.0F, 5.0F);
        this.back9.setTextureSize(64, 32);
        this.back9.mirror = true;
        this.setRotation(this.back9, 0.0F, 0.0F, -((float)Math.PI / 2F));
        this.back10 = new ModelRenderer(this, 42, 5);
        this.back10.addBox(0.0F, 0.0F, 0.0F, 8, 2, 2);
        this.back10.setRotationPoint(-10.0F, 4.0F, 5.0F);
        this.back10.setTextureSize(64, 32);
        this.back10.mirror = true;
        this.setRotation(this.back10, 0.0F, 0.0F, 0.0F);
        this.back11 = new ModelRenderer(this, 42, 5);
        this.back11.addBox(0.0F, 0.0F, 0.0F, 8, 2, 2);
        this.back11.setRotationPoint(2.0F, 4.0F, 5.0F);
        this.back11.setTextureSize(64, 32);
        this.back11.mirror = true;
        this.setRotation(this.back11, 0.0F, 0.0F, 0.0F);
        this.back12 = new ModelRenderer(this, 34, 26);
        this.back12.addBox(0.0F, 0.0F, 0.0F, 12, 2, 2);
        this.back12.setRotationPoint(2.0F, 6.0F, 4.0F);
        this.back12.setTextureSize(64, 32);
        this.back12.mirror = true;
        this.setRotation(this.back12, 0.0F, 0.0F, 0.6108652F);
    }

    /**
     * Sets the models various rotation angles then renders the model.
     */
    public void render(Entity var1, float var2, float var3, float var4, float var5, float var6, float var7)
    {
        super.render(var1, var2, var3, var4, var5, var6, var7);
        this.setRotationAngles(var2, var3, var4, var5, var6, var7);
        this.head.render(var7);
        this.body.render(var7);
        this.rightarmext.render(var7);
        this.leftarmext.render(var7);
        this.rightlegcap.render(var7);
        this.leftlegcap.render(var7);
        this.Shape1.render(var7);
        this.Shape2.render(var7);
        this.Shape3.render(var7);
        this.Shape4.render(var7);
        this.Shape5.render(var7);
        this.Shape6.render(var7);
        this.Shape7.render(var7);
        this.Shape8.render(var7);
        this.Shape9.render(var7);
        this.Shape10.render(var7);
        this.back.render(var7);
        this.back2.render(var7);
        this.back3.render(var7);
        this.back4.render(var7);
        this.leftleg.render(var7);
        this.rightleg.render(var7);
        this.leftarm.render(var7);
        this.rightarm.render(var7);
        this.leftfoot.render(var7);
        this.rightfoot.render(var7);
        this.back5.render(var7);
        this.back6.render(var7);
        this.back7.render(var7);
        this.back8.render(var7);
        this.back9.render(var7);
        this.back10.render(var7);
        this.back11.render(var7);
        this.back12.render(var7);
    }

    private void setRotation(ModelRenderer var1, float var2, float var3, float var4)
    {
        var1.rotateAngleX = var2;
        var1.rotateAngleY = var3;
        var1.rotateAngleZ = var4;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6)
    {
        this.rightarm.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarmext.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.leftarm.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarmext.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.rightarm.rotateAngleZ = 0.0F;
        this.leftarm.rotateAngleZ = 0.0F;
        this.rightleg.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.rightfoot.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.rightlegcap.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.leftleg.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 1.4F * var2;
        this.leftfoot.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 1.4F * var2;
        this.leftlegcap.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 1.4F * var2;
        this.rightleg.rotateAngleY = 0.0F;
        this.leftleg.rotateAngleY = 0.0F;
    }
}
