package xolova.blued00r.divinerpg.generation.vethea.layer1;

import java.util.Random;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import xolova.blued00r.divinerpg.DivineRPG;

public class Tree6 extends WorldGenerator
{
    protected int[] GetValidSpawnBlocks()
    {
        return new int[0];
    }

    public boolean generate(World var1, Random var2, int var3, int var4, int var5)
    {
        var1.setBlock(var3 + 0, var4 + 6, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 7, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 7, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 8, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 8, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 8, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 9, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 9, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 9, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 10, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 10, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 10, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 10, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 11, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 11, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 12, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 12, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 13, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 13, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 13, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 13, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 13, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 0, var4 + 13, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 1, var4 + 13, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 1, var4 + 13, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 1, var4 + 14, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 1, var4 + 14, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 1, var4 + 14, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 1, var4 + 14, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 0, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 0, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 1, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 1, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 2, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 2, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 3, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 3, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 4, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 4, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 5, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 5, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 6, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 6, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 7, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 7, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 7, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 8, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 8, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 8, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 9, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 9, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 10, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 10, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 10, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 11, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 11, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 11, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 11, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 12, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 12, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 12, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 13, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 13, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 13, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 2, var4 + 13, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 14, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 14, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 14, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 14, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 15, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 2, var4 + 15, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 0, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 0, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 1, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 1, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 2, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 2, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 3, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 3, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 4, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 4, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 5, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 5, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 6, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 6, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 6, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 7, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 7, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 8, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 8, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 8, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 9, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 9, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 9, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 10, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 10, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 10, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 11, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 11, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 11, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 11, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 12, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 12, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 13, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 13, var5 + 2, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 13, var5 + 3, DivineRPG.hyrewood.blockID);
        var1.setBlock(var3 + 3, var4 + 13, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 14, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 14, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 14, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 14, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 15, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 3, var4 + 15, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 6, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 7, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 8, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 10, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 11, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 12, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 13, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 13, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 14, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 14, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 14, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 4, var4 + 14, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 7, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 7, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 8, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 8, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 9, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 9, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 9, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 10, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 10, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 11, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 11, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 12, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 13, var5 + 0, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 13, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 13, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 13, var5 + 3, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 13, var5 + 4, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 5, var4 + 13, var5 + 5, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 7, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 8, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 8, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 9, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 10, var5 + 1, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 10, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 11, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 12, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        var1.setBlock(var3 + 6, var4 + 13, var5 + 2, DivineRPG.hyrewoodLeaves.blockID);
        return true;
    }
}
