package xolova.blued00r.divinerpg.client.models.entites.mobs.boss;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelParasecta extends ModelBase
{
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer bone1;
    ModelRenderer bone2;
    ModelRenderer bone3;
    ModelRenderer bone4;
    ModelRenderer bone5;
    ModelRenderer bone6;
    ModelRenderer bone7;
    ModelRenderer bone8;
    ModelRenderer bone9;
    ModelRenderer bone10;
    ModelRenderer bone11;
    ModelRenderer bone12;
    ModelRenderer bone13;
    ModelRenderer bone14;
    ModelRenderer bone15;
    ModelRenderer bone16;
    ModelRenderer bone17;
    ModelRenderer bone18;
    ModelRenderer bone19;
    ModelRenderer bone20;
    ModelRenderer bone21;
    ModelRenderer bone22;
    ModelRenderer bone23;
    ModelRenderer bone24;
    ModelRenderer nose;
    ModelRenderer wingR;
    ModelRenderer wingL;
    ModelRenderer wingRouter;
    ModelRenderer wingLouter;
    ModelRenderer ear1;
    ModelRenderer ear2;

    public ModelParasecta()
    {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.head = new ModelRenderer(this, 0, 15);
        this.head.addBox(-2.0F, -4.0F, -10.0F, 4, 2, 5);
        this.head.setRotationPoint(0.0F, 2.0F, -9.0F);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0F, 0.0F, 0.0F);
        this.body = new ModelRenderer(this, 38, 0);
        this.body.addBox(-6.0F, -10.0F, -7.0F, 10, 22, 3);
        this.body.setRotationPoint(1.0F, 1.0F, 3.0F);
        this.body.setTextureSize(64, 32);
        this.body.mirror = true;
        this.setRotation(this.body, 0.8644027F, 0.0F, 0.0F);
        this.bone1 = new ModelRenderer(this, 0, 0);
        this.bone1.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone1.setRotationPoint(-10.0F, 20.0F, 2.0F);
        this.bone1.setTextureSize(64, 32);
        this.bone1.mirror = true;
        this.setRotation(this.bone1, 0.0F, 0.0F, -((float)Math.PI / 4F));
        this.bone2 = new ModelRenderer(this, 0, 0);
        this.bone2.addBox(0.0F, 0.0F, 0.0F, 2, 8, 2);
        this.bone2.setRotationPoint(-10.0F, 12.0F, 2.0F);
        this.bone2.setTextureSize(64, 32);
        this.bone2.mirror = true;
        this.setRotation(this.bone2, 0.0F, 0.0F, 0.0F);
        this.bone3 = new ModelRenderer(this, 0, 0);
        this.bone3.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone3.setRotationPoint(-5.0F, 7.0F, 2.0F);
        this.bone3.setTextureSize(64, 32);
        this.bone3.mirror = true;
        this.setRotation(this.bone3, 0.0F, 0.0F, ((float)Math.PI / 4F));
        this.bone4 = new ModelRenderer(this, 0, 0);
        this.bone4.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone4.setRotationPoint(-10.0F, 18.0F, -1.0F);
        this.bone4.setTextureSize(64, 32);
        this.bone4.mirror = true;
        this.setRotation(this.bone4, 0.0F, 0.0F, -((float)Math.PI / 4F));
        this.bone5 = new ModelRenderer(this, 0, 0);
        this.bone5.addBox(0.0F, 0.0F, 0.0F, 2, 8, 2);
        this.bone5.setRotationPoint(-10.0F, 10.0F, -1.0F);
        this.bone5.setTextureSize(64, 32);
        this.bone5.mirror = true;
        this.setRotation(this.bone5, 0.0F, 0.0F, 0.0F);
        this.bone6 = new ModelRenderer(this, 0, 0);
        this.bone6.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone6.setRotationPoint(-5.0F, 5.0F, -1.0F);
        this.bone6.setTextureSize(64, 32);
        this.bone6.mirror = true;
        this.setRotation(this.bone6, 0.0F, 0.0F, ((float)Math.PI / 4F));
        this.bone7 = new ModelRenderer(this, 0, 0);
        this.bone7.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone7.setRotationPoint(-10.0F, 15.0F, -4.0F);
        this.bone7.setTextureSize(64, 32);
        this.bone7.mirror = true;
        this.setRotation(this.bone7, 0.0F, 0.0F, -((float)Math.PI / 4F));
        this.bone8 = new ModelRenderer(this, 0, 0);
        this.bone8.addBox(0.0F, 0.0F, 0.0F, 2, 8, 2);
        this.bone8.setRotationPoint(-10.0F, 7.0F, -4.0F);
        this.bone8.setTextureSize(64, 32);
        this.bone8.mirror = true;
        this.setRotation(this.bone8, 0.0F, 0.0F, 0.0F);
        this.bone9 = new ModelRenderer(this, 0, 0);
        this.bone9.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone9.setRotationPoint(-5.0F, 2.0F, -4.0F);
        this.bone9.setTextureSize(64, 32);
        this.bone9.mirror = true;
        this.setRotation(this.bone9, 0.0F, 0.0F, ((float)Math.PI / 4F));
        this.bone10 = new ModelRenderer(this, 0, 0);
        this.bone10.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone10.setRotationPoint(-5.0F, 0.0F, -7.0F);
        this.bone10.setTextureSize(64, 32);
        this.bone10.mirror = true;
        this.setRotation(this.bone10, 0.0F, 0.0F, ((float)Math.PI / 4F));
        this.bone11 = new ModelRenderer(this, 0, 0);
        this.bone11.addBox(0.0F, 0.0F, 0.0F, 2, 8, 2);
        this.bone11.setRotationPoint(-10.0F, 5.0F, -7.0F);
        this.bone11.setTextureSize(64, 32);
        this.bone11.mirror = true;
        this.setRotation(this.bone11, 0.0F, 0.0F, 0.0F);
        this.bone12 = new ModelRenderer(this, 0, 0);
        this.bone12.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone12.setRotationPoint(-10.0F, 13.0F, -7.0F);
        this.bone12.setTextureSize(64, 32);
        this.bone12.mirror = true;
        this.setRotation(this.bone12, 0.0F, 0.0F, -((float)Math.PI / 4F));
        this.bone13 = new ModelRenderer(this, 0, 0);
        this.bone13.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone13.setRotationPoint(8.0F, 11.1F, -7.0F);
        this.bone13.setTextureSize(64, 32);
        this.bone13.mirror = true;
        this.setRotation(this.bone13, 0.0F, 0.0F, ((float)Math.PI / 4F));
        this.bone14 = new ModelRenderer(this, 0, 0);
        this.bone14.addBox(0.0F, 0.0F, 0.0F, 2, 8, 2);
        this.bone14.setRotationPoint(7.4F, 4.6F, -7.0F);
        this.bone14.setTextureSize(64, 32);
        this.bone14.mirror = true;
        this.setRotation(this.bone14, 0.0F, 0.0F, 0.0F);
        this.bone15 = new ModelRenderer(this, 0, 0);
        this.bone15.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone15.setRotationPoint(3.0F, 1.0F, -7.0F);
        this.bone15.setTextureSize(64, 32);
        this.bone15.mirror = true;
        this.setRotation(this.bone15, 0.0F, 0.0F, -((float)Math.PI / 4F));
        this.bone16 = new ModelRenderer(this, 0, 0);
        this.bone16.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone16.setRotationPoint(8.0F, 14.1F, -4.0F);
        this.bone16.setTextureSize(64, 32);
        this.bone16.mirror = true;
        this.setRotation(this.bone16, 0.0F, 0.0F, ((float)Math.PI / 4F));
        this.bone17 = new ModelRenderer(this, 0, 0);
        this.bone17.addBox(0.0F, 0.0F, 0.0F, 2, 8, 2);
        this.bone17.setRotationPoint(7.4F, 7.6F, -4.0F);
        this.bone17.setTextureSize(64, 32);
        this.bone17.mirror = true;
        this.setRotation(this.bone17, 0.0F, 0.0F, 0.0F);
        this.bone18 = new ModelRenderer(this, 0, 0);
        this.bone18.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone18.setRotationPoint(3.0F, 4.0F, -4.0F);
        this.bone18.setTextureSize(64, 32);
        this.bone18.mirror = true;
        this.setRotation(this.bone18, 0.0F, 0.0F, -((float)Math.PI / 4F));
        this.bone19 = new ModelRenderer(this, 0, 0);
        this.bone19.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone19.setRotationPoint(8.0F, 19.1F, 2.0F);
        this.bone19.setTextureSize(64, 32);
        this.bone19.mirror = true;
        this.setRotation(this.bone19, 0.0F, 0.0F, ((float)Math.PI / 4F));
        this.bone20 = new ModelRenderer(this, 0, 0);
        this.bone20.addBox(0.0F, 0.0F, 0.0F, 2, 8, 2);
        this.bone20.setRotationPoint(7.4F, 12.6F, 2.0F);
        this.bone20.setTextureSize(64, 32);
        this.bone20.mirror = true;
        this.setRotation(this.bone20, 0.0F, 0.0F, 0.0F);
        this.bone21 = new ModelRenderer(this, 0, 0);
        this.bone21.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone21.setRotationPoint(3.0F, 9.0F, 2.0F);
        this.bone21.setTextureSize(64, 32);
        this.bone21.mirror = true;
        this.setRotation(this.bone21, 0.0F, 0.0F, -((float)Math.PI / 4F));
        this.bone22 = new ModelRenderer(this, 0, 0);
        this.bone22.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone22.setRotationPoint(8.0F, 16.1F, -1.0F);
        this.bone22.setTextureSize(64, 32);
        this.bone22.mirror = true;
        this.setRotation(this.bone22, 0.0F, 0.0F, ((float)Math.PI / 4F));
        this.bone23 = new ModelRenderer(this, 0, 0);
        this.bone23.addBox(0.0F, 0.0F, 0.0F, 2, 8, 2);
        this.bone23.setRotationPoint(7.4F, 9.6F, -1.0F);
        this.bone23.setTextureSize(64, 32);
        this.bone23.mirror = true;
        this.setRotation(this.bone23, 0.0F, 0.0F, 0.0F);
        this.bone24 = new ModelRenderer(this, 0, 0);
        this.bone24.addBox(0.0F, 0.0F, 0.0F, 2, 7, 2);
        this.bone24.setRotationPoint(3.0F, 6.0F, -1.0F);
        this.bone24.setTextureSize(64, 32);
        this.bone24.mirror = true;
        this.setRotation(this.bone24, 0.0F, 0.0F, -((float)Math.PI / 4F));
        this.nose = new ModelRenderer(this, 0, 15);
        this.nose.addBox(-4.0F, -4.0F, -6.0F, 8, 8, 9);
        this.nose.setRotationPoint(0.0F, -1.0F, -8.0F);
        this.nose.setTextureSize(64, 32);
        this.nose.mirror = true;
        this.setRotation(this.nose, 0.0F, 0.0F, 0.0F);
        this.wingR = new ModelRenderer(this, 0, 0);
        this.wingR.addBox(-16.0F, 0.0F, -6.0F, 16, 1, 13);
        this.wingR.setRotationPoint(-2.0F, 4.0F, 2.0F);
        this.wingR.setTextureSize(64, 32);
        this.wingR.mirror = true;
        this.setRotation(this.wingR, -((float)Math.PI * 2F / 9F), 0.0F, 0.0F);
        this.wingL = new ModelRenderer(this, 0, 0);
        this.wingL.addBox(0.0F, 0.0F, -6.0F, 16, 1, 13);
        this.wingL.setRotationPoint(2.0F, 4.0F, 2.0F);
        this.wingL.setTextureSize(64, 32);
        this.wingL.mirror = true;
        this.setRotation(this.wingL, -((float)Math.PI * 2F / 9F), 0.0F, 0.0F);
        this.wingRouter = new ModelRenderer(this, 0, 0);
        this.wingRouter.addBox(-16.0F, 0.0F, -6.0F, 16, 1, 13);
        this.wingRouter.setRotationPoint(-2.0F, 4.0F, 2.0F);
        this.wingRouter.setTextureSize(64, 32);
        this.wingRouter.mirror = true;
        this.setRotation(this.wingRouter, -0.8468461F, 0.5204921F, 0.5948606F);
        this.wingLouter = new ModelRenderer(this, 0, 0);
        this.wingLouter.addBox(0.0F, 0.0F, -6.0F, 16, 1, 13);
        this.wingLouter.setRotationPoint(2.0F, 4.0F, 2.0F);
        this.wingLouter.setTextureSize(64, 32);
        this.wingLouter.mirror = true;
        this.setRotation(this.wingLouter, -0.8468461F, -0.5205006F, -0.5948578F);
        this.ear1 = new ModelRenderer(this, 39, 7);
        this.ear1.addBox(-4.0F, -5.0F, 0.0F, 1, 3, 7);
        this.ear1.setRotationPoint(-1.0F, -2.0F, -8.0F);
        this.ear1.setTextureSize(64, 32);
        this.ear1.mirror = true;
        this.setRotation(this.ear1, 0.8922867F, 0.0F, 0.0F);
        this.ear2 = new ModelRenderer(this, 39, 7);
        this.ear2.addBox(4.0F, -5.0F, 0.0F, 1, 3, 7);
        this.ear2.setRotationPoint(0.0F, -2.0F, -8.0F);
        this.ear2.setTextureSize(64, 32);
        this.ear2.mirror = true;
        this.setRotation(this.ear2, 0.8922867F, 0.0F, 0.0F);
    }

    /**
     * Sets the models various rotation angles then renders the model.
     */
    public void render(Entity var1, float var2, float var3, float var4, float var5, float var6, float var7)
    {
        super.render(var1, var2, var3, var4, var5, var6, var7);
        this.setRotationAngles(var2, var3, var4, var5, var6, var7);
        this.head.render(var7);
        this.body.render(var7);
        this.bone1.render(var7);
        this.bone2.render(var7);
        this.bone3.render(var7);
        this.bone4.render(var7);
        this.bone5.render(var7);
        this.bone6.render(var7);
        this.bone7.render(var7);
        this.bone8.render(var7);
        this.bone9.render(var7);
        this.bone10.render(var7);
        this.bone11.render(var7);
        this.bone12.render(var7);
        this.bone13.render(var7);
        this.bone14.render(var7);
        this.bone15.render(var7);
        this.bone16.render(var7);
        this.bone17.render(var7);
        this.bone18.render(var7);
        this.bone19.render(var7);
        this.bone20.render(var7);
        this.bone21.render(var7);
        this.bone22.render(var7);
        this.bone23.render(var7);
        this.bone24.render(var7);
        this.nose.render(var7);
        this.wingR.render(var7);
        this.wingL.render(var7);
        this.wingRouter.render(var7);
        this.wingLouter.render(var7);
        this.ear1.render(var7);
        this.ear2.render(var7);
    }

    public void render(float var1)
    {
        this.head.render(var1);
        this.body.render(var1);
        this.bone1.render(var1);
        this.bone2.render(var1);
        this.bone3.render(var1);
        this.bone4.render(var1);
        this.bone5.render(var1);
        this.bone6.render(var1);
        this.bone7.render(var1);
        this.bone8.render(var1);
        this.bone9.render(var1);
        this.bone10.render(var1);
        this.bone11.render(var1);
        this.bone12.render(var1);
        this.bone13.render(var1);
        this.bone14.render(var1);
        this.bone15.render(var1);
        this.bone16.render(var1);
        this.bone17.render(var1);
        this.bone18.render(var1);
        this.bone19.render(var1);
        this.bone20.render(var1);
        this.bone21.render(var1);
        this.bone22.render(var1);
        this.bone23.render(var1);
        this.bone24.render(var1);
        this.nose.render(var1);
        this.wingR.render(var1);
        this.wingL.render(var1);
        this.wingRouter.render(var1);
        this.wingLouter.render(var1);
        this.ear1.render(var1);
        this.ear2.render(var1);
    }

    private void setRotation(ModelRenderer var1, float var2, float var3, float var4)
    {
        var1.rotateAngleX = var2;
        var1.rotateAngleY = var3;
        var1.rotateAngleZ = var4;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6)
    {
        this.wingR.rotateAngleY = MathHelper.cos(var4 * 1.3F) * (float)Math.PI * 0.25F;
        this.wingL.rotateAngleY = -this.wingR.rotateAngleY;
        this.wingRouter.rotateAngleY = this.wingR.rotateAngleY * 0.5F;
        this.wingLouter.rotateAngleY = -this.wingR.rotateAngleY * 0.5F;
    }
}
