package xolova.blued00r.divinerpg.client.models.entities.community;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelHungerHungry extends ModelBase
{
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarmm;
    ModelRenderer leftarmb;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer leftarmt;
    ModelRenderer leftarmm;
    ModelRenderer rightarmt;
    ModelRenderer rightarmb;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape7;
    ModelRenderer Shape6;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;

    public ModelHungerHungry()
    {
        this.textureWidth = 56;
        this.textureHeight = 64;
        this.head = new ModelRenderer(this, 0, 0);
        this.head.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8);
        this.head.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head.setTextureSize(56, 64);
        this.head.mirror = true;
        this.setRotation(this.head, -((float)Math.PI / 4F), 0.0F, 0.0F);
        this.body = new ModelRenderer(this, 16, 16);
        this.body.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4);
        this.body.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body.setTextureSize(56, 64);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0F, 0.0F, 0.0F);
        this.rightarmm = new ModelRenderer(this, 40, 16);
        this.rightarmm.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4);
        this.rightarmm.setRotationPoint(-5.0F, 7.0F, 0.5F);
        this.rightarmm.setTextureSize(56, 64);
        this.rightarmm.mirror = true;
        this.setRotation(this.rightarmm, 0.1745329F, 0.0F, ((float)Math.PI / 2F));
        this.leftarmb = new ModelRenderer(this, 40, 16);
        this.leftarmb.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4);
        this.leftarmb.setRotationPoint(3.0F, 9.0F, 0.5F);
        this.leftarmb.setTextureSize(56, 64);
        this.leftarmb.mirror = true;
        this.setRotation(this.leftarmb, 0.1745329F, 0.0F, -0.9250245F);
        this.rightleg = new ModelRenderer(this, 0, 16);
        this.rightleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.rightleg.setRotationPoint(-2.0F, 12.0F, 0.0F);
        this.rightleg.setTextureSize(56, 64);
        this.rightleg.mirror = true;
        this.setRotation(this.rightleg, 0.0F, 0.0F, 0.0F);
        this.leftleg = new ModelRenderer(this, 0, 16);
        this.leftleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.leftleg.setRotationPoint(2.0F, 12.0F, 0.0F);
        this.leftleg.setTextureSize(56, 64);
        this.leftleg.mirror = true;
        this.setRotation(this.leftleg, 0.0F, 0.0F, 0.0F);
        this.leftarmt = new ModelRenderer(this, 40, 16);
        this.leftarmt.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4);
        this.leftarmt.setRotationPoint(5.0F, 3.0F, 0.5F);
        this.leftarmt.setTextureSize(56, 64);
        this.leftarmt.mirror = true;
        this.setRotation(this.leftarmt, 0.1745329F, 0.0F, -2.042035F);
        this.leftarmm = new ModelRenderer(this, 40, 16);
        this.leftarmm.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4);
        this.leftarmm.setRotationPoint(5.0F, 7.0F, 0.5F);
        this.leftarmm.setTextureSize(56, 64);
        this.leftarmm.mirror = true;
        this.setRotation(this.leftarmm, 0.1745329F, 0.0F, -((float)Math.PI / 2F));
        this.rightarmt = new ModelRenderer(this, 40, 16);
        this.rightarmt.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4);
        this.rightarmt.setRotationPoint(-5.0F, 3.0F, 0.5F);
        this.rightarmt.setTextureSize(56, 64);
        this.rightarmt.mirror = true;
        this.setRotation(this.rightarmt, 0.1745329F, 0.0F, 2.042035F);
        this.rightarmb = new ModelRenderer(this, 40, 16);
        this.rightarmb.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4);
        this.rightarmb.setRotationPoint(-3.0F, 9.0F, 0.5F);
        this.rightarmb.setTextureSize(56, 64);
        this.rightarmb.mirror = true;
        this.setRotation(this.rightarmb, 0.1745329F, 0.0F, 0.9250245F);
        this.Shape1 = new ModelRenderer(this, 0, 32);
        this.Shape1.addBox(0.0F, 0.0F, -9.0F, 8, 2, 9);
        this.Shape1.setRotationPoint(-4.0F, 2.0F, -1.0F);
        this.Shape1.setTextureSize(56, 64);
        this.Shape1.mirror = true;
        this.setRotation(this.Shape1, 0.0F, 0.0F, 0.0F);
        this.Shape2 = new ModelRenderer(this, 0, 32);
        this.Shape2.addBox(0.0F, 0.0F, -7.0F, 6, 1, 8);
        this.Shape2.setRotationPoint(-3.0F, 1.0F, -2.0F);
        this.Shape2.setTextureSize(56, 64);
        this.Shape2.mirror = true;
        this.setRotation(this.Shape2, 0.0F, 0.0F, 0.0F);
        this.Shape3 = new ModelRenderer(this, 0, 32);
        this.Shape3.addBox(0.0F, 0.0F, -9.0F, 8, 2, 9);
        this.Shape3.setRotationPoint(-4.0F, 8.0F, -1.0F);
        this.Shape3.setTextureSize(56, 64);
        this.Shape3.mirror = true;
        this.setRotation(this.Shape3, 0.0F, 0.0F, 0.0F);
        this.Shape3.mirror = false;
        this.Shape4 = new ModelRenderer(this, 0, 32);
        this.Shape4.addBox(0.0F, 0.0F, -7.0F, 6, 1, 8);
        this.Shape4.setRotationPoint(-3.0F, 10.0F, -2.0F);
        this.Shape4.setTextureSize(56, 64);
        this.Shape4.mirror = true;
        this.setRotation(this.Shape4, 0.0F, 0.0F, 0.0F);
        this.Shape4.mirror = false;
        this.Shape5 = new ModelRenderer(this, 0, 0);
        this.Shape5.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape5.setRotationPoint(2.0F, 3.4F, -9.0F);
        this.Shape5.setTextureSize(56, 64);
        this.Shape5.mirror = true;
        this.setRotation(this.Shape5, 0.0F, 0.0F, 0.0F);
        this.Shape7 = new ModelRenderer(this, 0, 0);
        this.Shape7.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape7.setRotationPoint(-0.5F, 3.4F, -9.0F);
        this.Shape7.setTextureSize(56, 64);
        this.Shape7.mirror = true;
        this.setRotation(this.Shape7, 0.0F, 0.0F, 0.0F);
        this.Shape6 = new ModelRenderer(this, 0, 0);
        this.Shape6.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape6.setRotationPoint(-3.0F, 3.4F, -9.0F);
        this.Shape6.setTextureSize(56, 64);
        this.Shape6.mirror = true;
        this.setRotation(this.Shape6, 0.0F, 0.0F, 0.0F);
        this.Shape8 = new ModelRenderer(this, 0, 0);
        this.Shape8.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape8.setRotationPoint(2.0F, 3.4F, -7.0F);
        this.Shape8.setTextureSize(56, 64);
        this.Shape8.mirror = true;
        this.setRotation(this.Shape8, 0.0F, 0.0F, 0.0F);
        this.Shape9 = new ModelRenderer(this, 0, 0);
        this.Shape9.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape9.setRotationPoint(2.0F, 3.4F, -5.0F);
        this.Shape9.setTextureSize(56, 64);
        this.Shape9.mirror = true;
        this.setRotation(this.Shape9, 0.0F, 0.0F, 0.0F);
        this.Shape10 = new ModelRenderer(this, 0, 0);
        this.Shape10.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape10.setRotationPoint(-3.0F, 3.4F, -7.0F);
        this.Shape10.setTextureSize(56, 64);
        this.Shape10.mirror = true;
        this.setRotation(this.Shape10, 0.0F, 0.0F, 0.0F);
        this.Shape11 = new ModelRenderer(this, 0, 0);
        this.Shape11.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape11.setRotationPoint(-3.0F, 3.4F, -5.0F);
        this.Shape11.setTextureSize(56, 64);
        this.Shape11.mirror = true;
        this.setRotation(this.Shape11, 0.0F, 0.0F, 0.0F);
        this.Shape12 = new ModelRenderer(this, 0, 0);
        this.Shape12.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape12.setRotationPoint(-1.7F, 7.4F, -9.0F);
        this.Shape12.setTextureSize(56, 64);
        this.Shape12.mirror = true;
        this.setRotation(this.Shape12, 0.0F, 0.0F, 0.0F);
        this.Shape13 = new ModelRenderer(this, 0, 0);
        this.Shape13.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape13.setRotationPoint(2.0F, 7.4F, -6.0F);
        this.Shape13.setTextureSize(56, 64);
        this.Shape13.mirror = true;
        this.setRotation(this.Shape13, 0.0F, 0.0F, 0.0F);
        this.Shape14 = new ModelRenderer(this, 0, 0);
        this.Shape14.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape14.setRotationPoint(-3.0F, 7.4F, -6.0F);
        this.Shape14.setTextureSize(56, 64);
        this.Shape14.mirror = true;
        this.setRotation(this.Shape14, 0.0F, 0.0F, 0.0F);
        this.Shape15 = new ModelRenderer(this, 0, 0);
        this.Shape15.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape15.setRotationPoint(0.7F, 7.4F, -9.0F);
        this.Shape15.setTextureSize(56, 64);
        this.Shape15.mirror = true;
        this.setRotation(this.Shape15, 0.0F, 0.0F, 0.0F);
        this.Shape16 = new ModelRenderer(this, 0, 0);
        this.Shape16.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape16.setRotationPoint(2.0F, 7.4F, -8.0F);
        this.Shape16.setTextureSize(56, 64);
        this.Shape16.mirror = true;
        this.setRotation(this.Shape16, 0.0F, 0.0F, 0.0F);
        this.Shape17 = new ModelRenderer(this, 0, 0);
        this.Shape17.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
        this.Shape17.setRotationPoint(-3.0F, 7.4F, -8.0F);
        this.Shape17.setTextureSize(56, 64);
        this.Shape17.mirror = true;
        this.setRotation(this.Shape17, 0.0F, 0.0F, 0.0F);
    }

    /**
     * Sets the models various rotation angles then renders the model.
     */
    public void render(Entity var1, float var2, float var3, float var4, float var5, float var6, float var7)
    {
        super.render(var1, var2, var3, var4, var5, var6, var7);
        this.setRotationAngles(var2, var3, var4, var5, var6, var7);
        this.head.render(var7);
        this.body.render(var7);
        this.rightarmm.render(var7);
        this.leftarmb.render(var7);
        this.rightleg.render(var7);
        this.leftleg.render(var7);
        this.leftarmt.render(var7);
        this.leftarmm.render(var7);
        this.rightarmt.render(var7);
        this.rightarmb.render(var7);
        this.Shape1.render(var7);
        this.Shape2.render(var7);
        this.Shape3.render(var7);
        this.Shape4.render(var7);
        this.Shape5.render(var7);
        this.Shape7.render(var7);
        this.Shape6.render(var7);
        this.Shape8.render(var7);
        this.Shape9.render(var7);
        this.Shape10.render(var7);
        this.Shape11.render(var7);
        this.Shape12.render(var7);
        this.Shape13.render(var7);
        this.Shape14.render(var7);
        this.Shape15.render(var7);
        this.Shape16.render(var7);
        this.Shape17.render(var7);
    }

    private void setRotation(ModelRenderer var1, float var2, float var3, float var4)
    {
        var1.rotateAngleX = var2;
        var1.rotateAngleY = var3;
        var1.rotateAngleZ = var4;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6) {}
}
