package xolova.blued00r.divinerpg.client.models.vethea;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class Boheimite extends ModelBase
{
    ModelRenderer spine1;
    ModelRenderer bodyp1;
    ModelRenderer rightarmp1;
    ModelRenderer leftarmp1;
    ModelRenderer rightlegp1;
    ModelRenderer leftlegp1;
    ModelRenderer head;
    ModelRenderer spine2;
    ModelRenderer spine3;
    ModelRenderer spine4;
    ModelRenderer spine5;
    ModelRenderer spine6;
    ModelRenderer spine7;
    ModelRenderer spine9;
    ModelRenderer spine8;
    ModelRenderer spine10;
    ModelRenderer bodyp2;
    ModelRenderer bodyp3;
    ModelRenderer bodyp4;
    ModelRenderer bodyp5;
    ModelRenderer leftarm;
    ModelRenderer rightarm;
    ModelRenderer leftarmp2;
    ModelRenderer rightarmp2;
    ModelRenderer leftarmp3;
    ModelRenderer leftarmp4;
    ModelRenderer rightarmp3;
    ModelRenderer rightarmp4;
    ModelRenderer rightarmp5;
    ModelRenderer rightarmp6;
    ModelRenderer leftarmp5;
    ModelRenderer leftarmp6;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
    ModelRenderer rightlegp2;
    ModelRenderer leftlegp2;
    ModelRenderer leftarm7;
    ModelRenderer leftarm8;
    ModelRenderer rightarm7;
    ModelRenderer rightarm8;

    public Boheimite()
    {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.spine1 = new ModelRenderer(this, 45, 2);
        this.spine1.addBox(4.0F, -3.0F, -2.0F, 1, 2, 8);
        this.spine1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine1.setTextureSize(64, 32);
        this.spine1.mirror = true;
        this.setRotation(this.spine1, -0.2617994F, 0.0F, 0.0F);
        this.bodyp1 = new ModelRenderer(this, 16, 16);
        this.bodyp1.addBox(-4.0F, 0.0F, -2.0F, 5, 4, 4);
        this.bodyp1.setRotationPoint(4.0F, 4.0F, 0.0F);
        this.bodyp1.setTextureSize(64, 32);
        this.bodyp1.mirror = true;
        this.setRotation(this.bodyp1, 0.0F, 0.0F, 0.0F);
        this.bodyp1.mirror = false;
        this.rightarmp1 = new ModelRenderer(this, 32, 6);
        this.rightarmp1.addBox(1.0F, 10.0F, -17.0F, 1, 2, 7);
        this.rightarmp1.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarmp1.setTextureSize(64, 32);
        this.rightarmp1.mirror = true;
        this.setRotation(this.rightarmp1, 0.0F, 0.0F, 0.0F);
        this.leftarmp1 = new ModelRenderer(this, 32, 6);
        this.leftarmp1.addBox(3.0F, 10.0F, -17.0F, 1, 2, 7);
        this.leftarmp1.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarmp1.setTextureSize(64, 32);
        this.leftarmp1.mirror = true;
        this.setRotation(this.leftarmp1, 0.0F, 0.0F, 0.0F);
        this.rightlegp1 = new ModelRenderer(this, 17, 26);
        this.rightlegp1.addBox(-5.0F, 1.0F, -1.0F, 3, 3, 2);
        this.rightlegp1.setRotationPoint(-2.0F, 12.0F, 0.0F);
        this.rightlegp1.setTextureSize(64, 32);
        this.rightlegp1.mirror = true;
        this.setRotation(this.rightlegp1, 0.0F, 0.0F, 0.0F);
        this.leftlegp1 = new ModelRenderer(this, 17, 26);
        this.leftlegp1.addBox(2.0F, 1.0F, -1.0F, 3, 3, 2);
        this.leftlegp1.setRotationPoint(2.0F, 12.0F, 0.0F);
        this.leftlegp1.setTextureSize(64, 32);
        this.leftlegp1.mirror = true;
        this.head = new ModelRenderer(this, 0, 0);
        this.head.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8);
        this.head.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head.setTextureSize(64, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0F, 0.0F, 0.0F);
        this.spine2 = new ModelRenderer(this, 45, 2);
        this.spine2.addBox(0.0F, -5.0F, 6.0F, 1, 2, 8);
        this.spine2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine2.setTextureSize(64, 32);
        this.spine2.mirror = true;
        this.setRotation(this.spine2, 1.22173F, 0.0F, 0.0F);
        this.spine3 = new ModelRenderer(this, 45, 2);
        this.spine3.addBox(4.0F, -6.0F, 0.0F, 1, 2, 8);
        this.spine3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine3.setTextureSize(64, 32);
        this.spine3.mirror = true;
        this.setRotation(this.spine3, 0.1745329F, 0.0F, 0.0F);
        this.spine4 = new ModelRenderer(this, 45, 2);
        this.spine4.addBox(-5.0F, -3.0F, -2.0F, 1, 2, 8);
        this.spine4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine4.setTextureSize(64, 32);
        this.spine4.mirror = true;
        this.setRotation(this.spine4, -0.2617994F, 0.0F, 0.0F);
        this.spine5 = new ModelRenderer(this, 45, 2);
        this.spine5.addBox(-5.0F, -6.0F, 0.0F, 1, 2, 8);
        this.spine5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine5.setTextureSize(64, 32);
        this.spine5.mirror = true;
        this.setRotation(this.spine5, 0.1745329F, 0.0F, 0.0F);
        this.spine6 = new ModelRenderer(this, 45, 2);
        this.spine6.addBox(-5.0F, -8.0F, 1.0F, 1, 2, 8);
        this.spine6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine6.setTextureSize(64, 32);
        this.spine6.mirror = true;
        this.setRotation(this.spine6, 0.6108652F, 0.0F, 0.0F);
        this.spine7 = new ModelRenderer(this, 45, 2);
        this.spine7.addBox(4.0F, -8.0F, 1.0F, 1, 2, 8);
        this.spine7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine7.setTextureSize(64, 32);
        this.spine7.mirror = true;
        this.setRotation(this.spine7, 0.6108652F, 0.0F, 0.0F);
        this.spine9 = new ModelRenderer(this, 45, 2);
        this.spine9.addBox(2.0F, -7.0F, 4.0F, 1, 2, 8);
        this.spine9.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine9.setTextureSize(64, 32);
        this.spine9.mirror = true;
        this.setRotation(this.spine9, 0.9599311F, 0.0F, 0.0F);
        this.spine8 = new ModelRenderer(this, 45, 2);
        this.spine8.addBox(-3.0F, -7.0F, 4.0F, 1, 2, 8);
        this.spine8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine8.setTextureSize(64, 32);
        this.spine8.mirror = true;
        this.setRotation(this.spine8, 0.9599311F, 0.0F, 0.0F);
        this.spine10 = new ModelRenderer(this, 45, 2);
        this.spine10.addBox(-1.0F, -5.0F, 6.0F, 1, 2, 8);
        this.spine10.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.spine10.setTextureSize(64, 32);
        this.spine10.mirror = true;
        this.setRotation(this.spine10, 1.22173F, 0.0F, 0.0F);
        this.bodyp2 = new ModelRenderer(this, 16, 16);
        this.bodyp2.addBox(-4.0F, 0.0F, -2.0F, 8, 4, 4);
        this.bodyp2.setRotationPoint(-4.0F, 0.0F, 0.0F);
        this.bodyp2.setTextureSize(64, 32);
        this.bodyp2.mirror = true;
        this.setRotation(this.bodyp2, 0.0F, 0.0F, 0.0F);
        this.bodyp2.mirror = false;
        this.bodyp3 = new ModelRenderer(this, 16, 16);
        this.bodyp3.addBox(-4.0F, 0.0F, -2.0F, 8, 4, 4);
        this.bodyp3.setRotationPoint(0.0F, 8.0F, 0.0F);
        this.bodyp3.setTextureSize(64, 32);
        this.bodyp3.mirror = true;
        this.setRotation(this.bodyp3, 0.0F, 0.0F, 0.0F);
        this.bodyp4 = new ModelRenderer(this, 16, 16);
        this.bodyp4.addBox(-4.0F, 0.0F, -2.0F, 5, 4, 4);
        this.bodyp4.setRotationPoint(-1.0F, 4.0F, 0.0F);
        this.bodyp4.setTextureSize(64, 32);
        this.bodyp4.mirror = true;
        this.setRotation(this.bodyp4, 0.0F, 0.0F, 0.0F);
        this.bodyp5 = new ModelRenderer(this, 16, 16);
        this.bodyp5.addBox(-4.0F, 0.0F, -2.0F, 8, 4, 4);
        this.bodyp5.setRotationPoint(4.0F, 0.0F, 0.0F);
        this.bodyp5.setTextureSize(64, 32);
        this.bodyp5.mirror = true;
        this.setRotation(this.bodyp5, 0.0F, 0.0F, 0.0F);
        this.leftarm = new ModelRenderer(this, 40, 16);
        this.leftarm.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4);
        this.leftarm.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarm.setTextureSize(64, 32);
        this.leftarm.mirror = true;
        this.setRotation(this.leftarm, 0.0F, 0.0F, 0.0F);
        this.rightarm = new ModelRenderer(this, 40, 16);
        this.rightarm.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4);
        this.rightarm.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarm.setTextureSize(64, 32);
        this.rightarm.mirror = true;
        this.setRotation(this.rightarm, 0.0F, 0.0F, 0.0F);
        this.leftarmp2 = new ModelRenderer(this, 32, 6);
        this.leftarmp2.addBox(-2.0F, 10.0F, -17.0F, 1, 2, 7);
        this.leftarmp2.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarmp2.setTextureSize(64, 32);
        this.leftarmp2.mirror = true;
        this.setRotation(this.leftarmp2, 0.0F, 0.0F, 0.0F);
        this.rightarmp2 = new ModelRenderer(this, 32, 6);
        this.rightarmp2.addBox(-4.0F, 10.0F, -17.0F, 1, 2, 7);
        this.rightarmp2.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarmp2.setTextureSize(64, 32);
        this.rightarmp2.mirror = true;
        this.setRotation(this.rightarmp2, 0.0F, 0.0F, 0.0F);
        this.leftarmp3 = new ModelRenderer(this, 32, 6);
        this.leftarmp3.addBox(3.0F, 8.0F, -3.0F, 1, 2, 7);
        this.leftarmp3.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarmp3.setTextureSize(64, 32);
        this.leftarmp3.mirror = true;
        this.setRotation(this.leftarmp3, 0.0F, 0.0F, 0.0F);
        this.leftarmp4 = new ModelRenderer(this, 32, 6);
        this.leftarmp4.addBox(-2.0F, 8.0F, -3.0F, 1, 2, 7);
        this.leftarmp4.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarmp4.setTextureSize(64, 32);
        this.leftarmp4.mirror = true;
        this.setRotation(this.leftarmp4, 0.0F, 0.0F, 0.0F);
        this.rightarmp3 = new ModelRenderer(this, 32, 6);
        this.rightarmp3.addBox(1.0F, 8.0F, -3.0F, 1, 2, 7);
        this.rightarmp3.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarmp3.setTextureSize(64, 32);
        this.rightarmp3.mirror = true;
        this.setRotation(this.rightarmp3, 0.0F, 0.0F, 0.0F);
        this.rightarmp4 = new ModelRenderer(this, 32, 6);
        this.rightarmp4.addBox(-4.0F, 8.0F, -3.0F, 1, 2, 7);
        this.rightarmp4.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarmp4.setTextureSize(64, 32);
        this.rightarmp4.mirror = true;
        this.setRotation(this.rightarmp4, 0.0F, 0.0F, 0.0F);
        this.rightarmp5 = new ModelRenderer(this, 32, 6);
        this.rightarmp5.addBox(-4.0F, 8.0F, -10.0F, 1, 3, 7);
        this.rightarmp5.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarmp5.setTextureSize(64, 32);
        this.rightarmp5.mirror = true;
        this.setRotation(this.rightarmp5, 0.0F, 0.0F, 0.0F);
        this.rightarmp6 = new ModelRenderer(this, 32, 6);
        this.rightarmp6.addBox(1.0F, 8.0F, -10.0F, 1, 3, 7);
        this.rightarmp6.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarmp6.setTextureSize(64, 32);
        this.rightarmp6.mirror = true;
        this.setRotation(this.rightarmp6, 0.0F, 0.0F, 0.0F);
        this.leftarmp5 = new ModelRenderer(this, 32, 6);
        this.leftarmp5.addBox(-2.0F, 8.0F, -10.0F, 1, 3, 7);
        this.leftarmp5.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarmp5.setTextureSize(64, 32);
        this.leftarmp5.mirror = true;
        this.setRotation(this.leftarmp5, 0.0F, 0.0F, 0.0F);
        this.leftarmp6 = new ModelRenderer(this, 32, 6);
        this.leftarmp6.addBox(3.0F, 8.0F, -10.0F, 1, 3, 7);
        this.leftarmp6.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarmp6.setTextureSize(64, 32);
        this.leftarmp6.mirror = true;
        this.setRotation(this.leftarmp6, 0.0F, 0.0F, 0.0F);
        this.leftleg = new ModelRenderer(this, 0, 16);
        this.leftleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.leftleg.setRotationPoint(2.0F, 12.0F, 0.0F);
        this.leftleg.setTextureSize(64, 32);
        this.leftleg.mirror = true;
        this.setRotation(this.leftleg, 0.0F, 0.0F, 0.0F);
        this.rightleg = new ModelRenderer(this, 0, 16);
        this.rightleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4);
        this.rightleg.setRotationPoint(-2.0F, 12.0F, 0.0F);
        this.rightleg.setTextureSize(64, 32);
        this.rightleg.mirror = true;
        this.setRotation(this.rightleg, 0.0F, 0.0F, 0.0F);
        this.rightlegp2 = new ModelRenderer(this, 28, 26);
        this.rightlegp2.addBox(-5.0F, 6.0F, -1.0F, 3, 3, 2);
        this.rightlegp2.setRotationPoint(-2.0F, 12.0F, 0.0F);
        this.rightlegp2.setTextureSize(64, 32);
        this.rightlegp2.mirror = true;
        this.setRotation(this.rightlegp2, 0.0F, 0.0F, 0.0F);
        this.leftlegp2 = new ModelRenderer(this, 28, 26);
        this.leftlegp2.addBox(2.0F, 6.0F, -1.0F, 3, 3, 2);
        this.leftlegp2.setRotationPoint(2.0F, 12.0F, 0.0F);
        this.leftlegp2.setTextureSize(64, 32);
        this.leftlegp2.mirror = true;
        this.setRotation(this.leftlegp2, 0.0F, 0.0F, 0.0F);
        this.leftarm7 = new ModelRenderer(this, 32, 6);
        this.leftarm7.addBox(3.0F, 8.0F, -17.0F, 1, 2, 7);
        this.leftarm7.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarm7.setTextureSize(64, 32);
        this.leftarm7.mirror = true;
        this.setRotation(this.leftarm7, 0.0F, 0.0F, 0.0F);
        this.leftarm8 = new ModelRenderer(this, 32, 6);
        this.leftarm8.addBox(-2.0F, 8.0F, -17.0F, 1, 2, 7);
        this.leftarm8.setRotationPoint(9.0F, 2.0F, 0.0F);
        this.leftarm8.setTextureSize(64, 32);
        this.leftarm8.mirror = true;
        this.setRotation(this.leftarm8, 0.0F, 0.0F, 0.0F);
        this.rightarm7 = new ModelRenderer(this, 32, 6);
        this.rightarm7.addBox(1.0F, 8.0F, -17.0F, 1, 2, 7);
        this.rightarm7.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarm7.setTextureSize(64, 32);
        this.rightarm7.mirror = true;
        this.setRotation(this.rightarm7, 0.0F, 0.0F, 0.0F);
        this.rightarm8 = new ModelRenderer(this, 32, 6);
        this.rightarm8.addBox(-4.0F, 8.0F, -17.0F, 1, 2, 7);
        this.rightarm8.setRotationPoint(-9.0F, 2.0F, 0.0F);
        this.rightarm8.setTextureSize(64, 32);
        this.rightarm8.mirror = true;
        this.setRotation(this.rightarm8, 0.0F, 0.0F, 0.0F);
    }

    /**
     * Sets the models various rotation angles then renders the model.
     */
    public void render(Entity var1, float var2, float var3, float var4, float var5, float var6, float var7)
    {
        super.render(var1, var2, var3, var4, var5, var6, var7);
        this.setRotationAngles(var2, var3, var4, var5, var6, var7);
        this.spine1.render(var7);
        this.bodyp1.render(var7);
        this.rightarmp1.render(var7);
        this.leftarmp1.render(var7);
        this.rightlegp1.render(var7);
        this.leftlegp1.render(var7);
        this.head.render(var7);
        this.spine2.render(var7);
        this.spine3.render(var7);
        this.spine4.render(var7);
        this.spine5.render(var7);
        this.spine6.render(var7);
        this.spine7.render(var7);
        this.spine9.render(var7);
        this.spine8.render(var7);
        this.spine10.render(var7);
        this.bodyp2.render(var7);
        this.bodyp3.render(var7);
        this.bodyp4.render(var7);
        this.bodyp5.render(var7);
        this.leftarm.render(var7);
        this.rightarm.render(var7);
        this.leftarmp2.render(var7);
        this.rightarmp2.render(var7);
        this.leftarmp3.render(var7);
        this.leftarmp4.render(var7);
        this.rightarmp3.render(var7);
        this.rightarmp4.render(var7);
        this.rightarmp5.render(var7);
        this.rightarmp6.render(var7);
        this.leftarmp5.render(var7);
        this.leftarmp6.render(var7);
        this.leftleg.render(var7);
        this.rightleg.render(var7);
        this.rightlegp2.render(var7);
        this.leftlegp2.render(var7);
        this.leftarm7.render(var7);
        this.leftarm8.render(var7);
        this.rightarm7.render(var7);
        this.rightarm8.render(var7);
    }

    private void setRotation(ModelRenderer var1, float var2, float var3, float var4)
    {
        var1.rotateAngleX = var2;
        var1.rotateAngleY = var3;
        var1.rotateAngleZ = var4;
    }

    public void setRotationAngles(float var1, float var2, float var3, float var4, float var5, float var6)
    {
        this.leftleg.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.leftlegp1.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 1.4F * var2;
        this.rightleg.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 1.4F * var2;
        this.rightlegp2.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 1.4F * var2;
        this.rightarm.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarmp1.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarmp2.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarmp3.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarmp4.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarmp5.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarmp6.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarm7.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.rightarm8.rotateAngleX = MathHelper.cos(var1 * 0.6662F + (float)Math.PI) * 2.0F * var2 * 0.5F;
        this.leftarm.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarmp1.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarmp2.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarmp3.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarmp4.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarmp5.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarmp6.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarm7.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
        this.leftarm8.rotateAngleX = MathHelper.cos(var1 * 0.6662F) * 2.0F * var2 * 0.5F;
    }
}
